### PR TITLE
Expose NoFetch to fix #646

### LINKED ISSUE #646: GitVersionTask 3.1.2 tries to fetch on VsoAgent
On my CI server on VSO, I use both the GitVersionVsoTask and the GitVersionTask for MSBuild. The reason is that I want local builds to have assembly info's updated. 

For now, I get the following warnings when the git version task runs on the VSO agent. I don't think it's getting a nofetch param:

```
3>MSBUILD : warning : WARN [09/16/15 8:31:47:34] Could not determine assembly version: Request failed with status code: 401 [f:\a1\91fa088d\MT\ViewModels\ViewModels.csproj]

348 
2015-09-16T12:31:47.3561791Z          INFO [09/16/15 8:31:47:34] CacheKey: f:\a1\91fa088d\MT\.git:refs/heads/release-3.0.0:be52ac789210c8f72a3943d078bef9726775b1e9

349 
2015-09-16T12:31:47.3561791Z          INFO [09/16/15 8:31:47:34] Version not in cache. Calculating version.

350 
2015-09-16T12:31:47.3561791Z          INFO [09/16/15 8:31:47:34] Applicable build agent found: 'VsoAgent'.

351 
2015-09-16T12:31:47.3561791Z          INFO [09/16/15 8:31:47:34] Branch from build environment: refs/heads/release-3.0.0

352 
2015-09-16T12:31:47.3561791Z          INFO [09/16/15 8:31:47:34] One remote found (origin -> 'https://.....visualstudio.com/DefaultCollection/....').

353 
2015-09-16T12:31:47.3561791Z          INFO [09/16/15 8:31:47:34] Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.

354 
2015-09-16T12:31:47.5124075Z ##[warning]WARN [09/16/15 8:31:47:49] Could not determine assembly version: Request failed with status code: 401

355 
2015-09-16T12:31:47.5124075Z      3>MSBUILD : warning : WARN [09/16/15 8:31:47:49] Could not determine assembly version: Request failed with status code: 401 [f:\a1\91fa088d\MT\ViewModels\ViewModels.csproj]
```

### PR DESCRIPTION
**Pull request by onovotny**

### CODE REVIEW

**Comment by onovotny** [comment]
Confirmed this works on VSO if I then set GitVersion_NoFetchEnabled to true in the build parameters

**Comment by onovotny** [comment]
Do you think the targets should detect if they're running on an agent that requires nofetch (like VSO) and set the default value to true? Then it'd "just work" for more people but it does put extra logic in the targets.

**Comment by JakeGinnivan** [comment]
No the targets, the targets is like command line switches. 

I forget where I wrote this, but my plan was to add `bool? CanFetch` to https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/BuildServers/IBuildServer.cs#L12 or something similar. Because each build server implementation knows if it needs dynamic repositories or cannot fetch

**Comment by onovotny** [comment]
It is a better idea to have a the IBuildServer tell you if it needs fetching. If it's set there and used anywhere the NoFetch parameter currently is as a default if NoFetch isn't explicitly set, then that's a better solution.

I was just thinking that people shouldn't have to specifically override things on the happy path :)

**Pull request merged**
