### PR TITLE
Add ExcludeFromCodeCoverage attribute on top of generated GitVersionI…

### PR DESCRIPTION
**Pull request by odalet**
…nformation classes

## Description

This decorates generated code with `ExcludeFromCodeCoverage` attribute so that it does not participate in code coverage statistics.  

## Related Issue

#2305

## Motivation and Context

This prevents generated code from being detected as 'not covered'. Generated code should not be part of code coverage statistics.

## How Has This Been Tested?

In order to make sure adding this attribute resulted in 100% coverage, I crafted a simple solution with a VB.NET, a C# and a F# project + a unit test. This project is available here: <https://github.com/odalet/GitVersionTests>

I couldn't achieve 100% coverage on the F# lib and detected a potential issue on the VB project. I describe these below in subsequent comments because I don't really know what way to go with these and then am opening discussions.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by odalet** [comment]
So here is the problem with the VB.NET Generated code:
because it is not part of any namespace, it gets generated into the assembly's default namespace, not its 'global' namespace:

image

I suggest to enclose the generated code into this so that it behaves like the C# code:

```vb.net
Namespace Global
... existing class template
End Namespace
```

This change is not part of this PR because I wonder if I should propose another PR for this

**Comment by odalet** [comment]
Concerning F#, it is a bit more tricky. Modules seem to generate plenty of stuff that is _not_ inheriting the `ExcludeFromCodeCoverage` attribute:

image

For now, I managed to achieve 100% coverage by changing the F# module into a static class. Something like that:

```fsharp
namespace global

[<AbstractClass; Sealed>]
[<global.System.Runtime.CompilerServices.CompilerGenerated>]
[<System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>]
type GitVersionInformation() =
    static member Major = "1"
    static member Minor = "2"
    static member Patch = "3"
   ...
```

However, this being quite a big change, I didn't pushed it yet. Waiting for approval here.

**Comment by odalet** [comment]
You're welcome! And what about the 2 other issues I mention above? Could you have a look at them?Should I open dedicated issues?

**Comment by asbjornu** [comment]
Yes, please open one PR per issue. I think both solutions look good, I'm just a bit unsure about the backwards compatibility of them, so let's discuss that in each provided PR.

**Comment by odalet** [comment]
True, both issues may raise compatibility concerns. I'll do just that and open issues when I find some time!

**Pull request merged**
