### PR TITLE
adds Preview suffix to VSIX task name when appropriate

### PR DESCRIPTION
**Pull request by thoemmi**
Currently the GitVersion tasks from the release and the preview extension are named "GitVersion Task". If both extensions are installed, you cannot distinguish them by name.

This PR adds a " (Preview)" suffix to the task's displayname, just like it's already done for the extension itself.

### CODE REVIEW

**Comment by arturcic** [comment]
Looks good to me! Thanks for the PR. I'll merge the changes when the build finishes

**Comment by thoemmi** [comment]
I'am afraid the name of my branch is too long, the AppVeyor build failed with
```
Executing: "C:/ProgramData/chocolatey/bin/Choco.exe" pack -v -y --version "5.1.0-add-preview-suffix-1-203" "C:/projects/gitversion/nuspec/GitVersion.Portable.temp.nuspec"
Chocolatey v0.10.15
Attempting to build package from 'GitVersion.Portable.temp.nuspec'.
The special version part cannot exceed 20 characters.
An error occurred when executing task 'Pack-Chocolatey'
```

**Comment by arturcic** [comment]
if Azure pipelines succeeds I'll merge. Appveyor is only for backup

**Comment by arturcic** [comment]
Thank you so much for your contributions, @thoemmi 👍 . The the build finishes you should uninstall and install the extension, if you want to see the change

**Pull request merged**
