### PR TITLE
Pre-release label in git tag

### LINKED ISSUE #1255: The same version generated twice
I have stumbled on smth that looks like a bug to me .

Given this configuration (abbreviated from my unit tests for gitversion.yml):

```
next-version: 5.0
branches:
  master:
    regex: master
    tag: beta
    increment: Patch
    mode: ContinuousDeployment
```
I am getting this in my unit test log:

```
0001 Initial commit - expect beta.0
     git init .
     commit = True
          SemVer:               5.0.0-beta.0
          FullSemVer:           5.0.0-beta.0
          AssemblySemVer:       5.0.0.0
          AssemblySemFileVer:   5.0.0.0
          InformationalVersion: 5.0.0-beta.0+Branch.master.Sha.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

0002 No committed changes - expect beta.0
     commit = False
          SemVer:               5.0.0-beta.0
          FullSemVer:           5.0.0-beta.0
          AssemblySemVer:       5.0.0.0
          AssemblySemFileVer:   5.0.0.0
          InformationalVersion: 5.0.0-beta.0+Branch.master.Sha.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

0003 Commit changes - expect beta.1
     commit = True
          SemVer:               5.0.0-beta.1
          FullSemVer:           5.0.0-beta.1
          AssemblySemVer:       5.0.0.0
          AssemblySemFileVer:   5.0.0.0
          InformationalVersion: 5.0.0-beta.1+Branch.master.Sha.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

0004 Another commit - expect beta.2
     commit = True
          SemVer:               5.0.0-beta.2
          FullSemVer:           5.0.0-beta.2
          AssemblySemVer:       5.0.0.0
          AssemblySemFileVer:   5.0.0.0
          InformationalVersion: 5.0.0-beta.2+Branch.master.Sha.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

0005 Create tag for the release candidate 1, no changes committed after the tag
     git tag v5.0.0-rc.1
     commit = False
          SemVer:               5.0.0-rc.1
          FullSemVer:           5.0.0-rc.1
          AssemblySemVer:       5.0.0.0
          AssemblySemFileVer:   5.0.0.0
          InformationalVersion: 5.0.0-rc.1+Branch.master.Sha.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

0006 Simple commit - expect 5.0.1-beta.1
     commit = True
          SemVer:               5.0.0-beta.1
          FullSemVer:           5.0.0-beta.1
          AssemblySemVer:       5.0.0.0
          AssemblySemFileVer:   5.0.0.0
          InformationalVersion: 5.0.0-beta.1+Branch.master.Sha.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

Note that in step 0003 and 0006 gitversion has returned the same semantic version:  *5.0.0-beta.1*
And then it continues the count, duplicating beta.2 and so on.

I see two problems with the observed behaviour:

- Gitversion generated non-unique version numbers which violates a pronciple of unique identification
- Gitversion generated a lower version after the higher one, which breaks correct sorting order (*5.0.0-rc.1* is higher than *5.0.0-beta.1*)

There is also an inconsistency: in step 0001 it started to count beta from 0 (which surprised me), but after the RC in step 0006 it started to count beta from 1.

In addition (I do not show this in the log to keep things simpler) after +semver:fix even though the patch number was increased, the beta suffix did not restart the count, which IMHO is not the right behaviour.

I am testing against version: 
`4.0.0-beta.12+1315.Branch.master.Sha.9c70946f68973b3b31b2861913c247fbe6c3f0ec`

I would expect GitVersion to figure out that it needs to increase the version as every 5.0.0-beta would be lower than 5.0.0-rc.1, so given my configuration it should bump the patch number and re-start the beta count. Using this logic, the expected version would be: *5.0.1-beta.1*

Any tips on how to get the configuration right will be appreciated, as I need to come up with working configuration for a team adopting this tool. I have only started to learn about gitversion; maybe I am not using it correctly?

### PR DESCRIPTION
**Pull request by asbjornu**
Rebase and conflict resolvement of #1261. Resolves #1261, fixes #1255.

### CODE REVIEW

**Comment by ruhullahshah** [comment]
The reason for the observed incorrect version number is that GitVersion is somehow sensitive to tags are of the form `v5.0.0-rc.1` or `v5.0.0-beta.1`. In case the `PreReleaseTag` is dropped from the Git tag, for instance naming the tag simply as `v5.0.0` leads to a successful execution of the testcase reported here.

I see that the chosen versioning strategy is correct. however, this part of the [code](https://github.com/GitTools/GitVersion/blob/14b736584840bae5878b565e7d92caea6afc6c7d/src/GitVersionCore/SemanticVersion.cs#L293) causes an incorrect version increment, even though it is set to `Patch`. I think that this part of the code would generally hold true, for instance, bumping the version number on `develop` from `5.0.0-alpha.1` to `5.0.0-alpha.2`, but in this case it is doing the wrong thing.

Any thoughts?

**Comment by asbjornu** [comment]
Thanks for digging into this, @ruhullahshah. I'm a bit confused, since the tag should only take presedence if it is on the current commit. For the test case in this PR, there is a commit after the tag `v5.0.0-rc.1` is added, so according to my understanding, we should end up on [this `case VersionField.Patch`](https://github.com/GitTools/GitVersion/blob/14b736584840bae5878b565e7d92caea6afc6c7d/src/GitVersionCore/SemanticVersion.cs#L308). However, that does not seem to be the case.

**Comment by ruhullahshah** [comment]
@asbjornu  You are welcome.  Your argument is correct, if the tag name did not have `PreReleaseTag` in its name. However, (this)[https://github.com/GitTools/GitVersion/blob/14b736584840bae5878b565e7d92caea6afc6c7d/src/GitVersionCore/SemanticVersion.cs#L293] line of code will not allow it to pass through. Try removing the `-rc*` from the test and everything works as expected.

**Comment by asbjornu** [comment]
Aha, I was caught yet again by the naming confusion discussed in #1054. I instinctively think of `git tag` every time I read `PreReleaseTag`, which is why I argue in #1054 that it should be called `PreReleaseLabel` instead. Okay, so in the presence of a pre-release label, the label's `Number` will be incremented instead of applying the chosen increment strategy. I'm not sure why that should be correct for any other commits than the one where the `git tag` is applied, though. So my thought is still the same: Why should the pre-release label affect the increment strategy at all?

**Comment by asbjornu** [comment]
Also, when thinking of how the test is formulated and https://github.com/GitTools/GitVersion/issues/1255#issuecomment-465548324, isn't `mode: Mainline` more appropriate for the given use case? I'll test how it affects the version number.

**Comment by asbjornu** [comment]
Nope, [`mode: Mainline` does not support pre-release labels](https://ci.appveyor.com/project/GitTools/gitversion/builds/22682682#L253): `System.NotSupportedException : Mainline development mode doesn't yet support pre-release tags on master`.

I still think `mode: Mainline` is correct for the use case, but we don't support the given use case with `Mainline`. 🤷‍♂️

**Comment by ruhullahshah** [comment]
Your questions are valid and relate more to the specifications and usage of GitVersion. It "might" be true that in this particular case, GitVersion is abused. However,  I would like to demonstrate the general problem with a simpler test case:
```csharp
[Test]
public void ShouldProvideTheCorrectVersionEvenIfPreReleaseLabelExistsInTheGitTag()
{
    using (var fixture = new EmptyRepositoryFixture())
    {
        fixture.Repository.MakeACommit();
        fixture.ApplyTag("1.0.0-oreo.1");
        fixture.BranchTo("develop");
        fixture.Repository.MakeACommit();
        fixture.AssertFullSemver("1.1.0-alpha.1");
    }
}
```
This simple test fails due to the presence of a `PreReleaseLabel` (I agree that this is a better naming convention)  in the `git tag`

**Comment by asbjornu** [comment]
Great point, @ruhullahshah. I've added your test to this PR as further proof that something needs to be done about this. I'm just not sure what.

**Comment by ermshiperete** [comment]
#1844/ #1845 seem to be related

**Comment by arturcic** [comment]
Closed in favor of #3445

**Pull request closed without merging**
