### PR TITLE
Add handling of Assembly attributes that do not end on a new line

### LINKED ISSUE #1939: Commented out AssemblyVersion tags still causing GitVersion to not generate versions correctly
Hi All,

I found the following problem.  I installed GitVersionTask, and commented out my AssemblyVersion tags from my AssemblyInfo.cs file.

After building, GitVersion would version my dll as 0.0.0.0.

I received the warning:

`File contains assembly version attributes which conflict with the attributes generated by GitVersion`

I looked in the code for the detection, and it looks like it expects a full line, https://github.com/GitTools/GitVersion/blob/2dd6bd1aa664d41814dab83b0a6d4f97b28807a9/src/GitVersionTask/FileHelper.cs#L108

My AssemblyInfo.cs looks like this:

```
//[assembly: AssemblyVersion("1.0.*")]
//[assembly: AssemblyFileVersion("19.04.15")]
//[assembly: AssemblyInformationalVersion("19.04.15-1822afec")][END OF FILE]
```

Updating my AssemblyInfo to the following did the trick:

```
//[assembly: AssemblyVersion("1.0.*")]
//[assembly: AssemblyFileVersion("19.04.15")]
//[assembly: AssemblyInformationalVersion("19.04.15-1822afec")]
[END OF FILE]
```

Not sure if you want to fix this, but here it is anyway, in case someone else runs into the same problem.

Cheers,

### PR DESCRIPTION
**Pull request by KiLLeRRaT**
- Added tests that fail if we don't have a newline after Assembly attributes
- Updated FileHelper to support commented out Assembly attributes that do not end with a new line

Fixes #1939 and #1802.

### CODE REVIEW

**Comment by arturcic** [comment]
Will this fix this issue as well? https://github.com/GitTools/GitVersion/issues/1802

**Comment by asbjornu** [comment]
I think we should merge this and see whether #2102 turns green. 👍

**Comment by arturcic** [comment]
Ok @asbjornu

**Comment by asbjornu** [comment]
Thank you for your contributions @KiLLeRRaT! 🙏

**Comment by KiLLeRRaT** [comment]
@asbjornu Not a problem, happy to help.  

Eagerly waiting on some of the other issues/PRs to be finalised and sorted out so I can upgrade my projects to ust 5.1.4. (I'm stuck with .NET472, build issues etc.  Should be dealt to with some of the other PRs).

Have a good one!

**Pull request merged**
