### PR TITLE
Refactoring of merge message class

### PR DESCRIPTION
**Pull request by Kieranties**
Refactoring of the `MergeMessage` class to enable simpler (and consistent) approach to adding new regular expressions.  This is a prelude to an additional PR where I hope to enable custom patterns through config.

- All patterns are now stored in a collection.  The collection is enumerated to apply the order in which they are checked (currently the same order previously used)
- Each pattern has a required _SourceBranch_ capture group
- Pull request patterns have a required _PullRequestNumber_ capture group
- All patterns (except Bit Bucket pull request) have an optional _TargetBranch_ capture group.  _TargetBranch_ is required for Bit Bucket pull requests

This introduces the following **breaking changes**:

| Merge message | Previous result | Breaking Change |
| --- | --- | --- | 
| Merge pull request # from feature/one | Pull Request Number = 0 <br /> Merged Branch = feature/one |  **No match** |
| Merge pull request # in feature/one from feature/two to master | Pull Request Number = 0 <br /> Merged Branch = feature/two <br /> Target Branch = master | **No match** |
| Merge pull request #1234 from feature/one into dev | Pull Request Number = 1234 <br /> Merged Branch = **feature/one into dev** <br /> Target Branch = dev| Pull Request Number = 1234 <br /> Merged Branch = **feature/one** <br /> Target Branch = dev|
| Merge pull request #1234 from feature/one from feature/two to master | Pull Request Number = 1234 <br /> Merged Branch = feature/two <br /> Target Branch = **null** | Pull Request Number = 1234 <br /> Merged Branch = feature/two <br /> Target Branch = **master** |
| Finish V4.0.0 into master | Merged Branch = **V4.0.0 into master** <br /> Target Branch = master | Merged Branch = **V4.0.0** <br /> Target Branch = master |

### CODE REVIEW

**Comment by Kieranties** [comment]
@asbjornu I've pre-emptively raised #1488 which introduces the actual feature set I've been working towards.  It favours `KeyValuePair` over the custom class but does have a dependency on the breaking changes in this request.  

If you're happy with the breaking changes, should I close this and move the breaking change info into that request?

**Comment by asbjornu** [comment]
@Kieranties: No, we'll keep this open for a few days before merging so @GitTools/developers can have a chance to review it. If I hear nothing, I'll merge and you can rebase #1488 on `master` afterwards.

**Comment by asbjornu** [comment]
@Kieranties: Since we've now decided to bump the major version due to other breaking changes, I would highly appreciate if you could rebase this PR and fix the merge conflicts. 🙏

**Comment by Kieranties** [comment]
@asbjornu I'm tied up for a few days, but will get this done.  I'll also rebase/update #1488.

**Comment by asbjornu** [comment]
@Kieranties: Excellent!

**Comment by Kieranties** [comment]
@asbjornu Rebase complete.  Let me know of any issues.  If the PR gets completed I'll do the follow up work on #1488.  There are some additional tests added to cater for the TFS merge messages.

**Comment by Kieranties** [comment]
@asbjornu I see this is out of date again.  I've updated my branch to chase things up.

**Comment by asbjornu** [comment]
Thanks, @Kieranties. 🙏

**Comment by Kieranties** [comment]
Awesome!  I'll get #1488 fixed up this evening!

**Pull request merged**
