### PR TITLE
Fixes #1430 - gitreleasenotes step.

### LINKED ISSUE #1430: Appveyor build failing on master
After merging PR #1269 the appveyor build fails at cake step to do with git release notes.

https://ci.appveyor.com/project/GitTools/gitversion/branch/master

Needs fixing.

### PR DESCRIPTION
**Pull request by dazinator**
Corrected path to git release notes to fix build.

### CODE REVIEW

**Comment by gep13** [comment]
@dazinator I am surprised that this addition is needed, but I suspect that it is due to changes in the way that NuGet Addins/Tools are resolved.

This changed in a recent version of Cake.

**Comment by gep13** [comment]
@dazinator yeah, that didn't work :-(

The correct path to the file is:

`tools\GitReleaseNotes.0.7.0\tools\GitReleaseNotes.exe`

**Comment by gep13** [comment]
@dazinator  Can I suggest using something like this:

    FilePath gitReleaseNotesPath = Context.Tools.Resolve("GitReleaseNotes.exe");

Which will return:

`C:/github_local/organisations/gittools/GitVersion/tools/GitReleaseNotes.0.7.0/tools/GitReleaseNotes.exe`

To save having to hard code the path?

**Comment by dazinator** [comment]
Odd - that's what the path id for me locally:

image

I'll change it to your suggestion :-)

**Comment by arturcic** [comment]
can we use the cake addin as is? https://cakebuild.net/api/Cake.Common.Tools.GitReleaseNotes/GitReleaseNotesAliases/

**Comment by gep13** [comment]
@dazinator I am going to go out on a limb and say that you have got an old version of Cake locally on your machine.

image

If you go into the tools folder and then the Cake folder and right click on the Cake.exe, what version does it say you have?

**Pull request merged**
