### PR TITLE
GH1055: Removed commas from tags section

### PR DESCRIPTION
**Pull request by gep13**
Relates to #1055

### CODE REVIEW

**Comment by gep13** [comment]
@asbjornu this is why the Chocolatey Package isn't up to date.

Can you take a look at the changes when you have a minute?  Thanks!

**Comment by gep13** [comment]
@asbjornu @JakeGinnivan @pascalberger fairly sure the build failure is a red herring here.

But let me know if there is something else that needs to happen.

**Comment by asbjornu** [comment]
@gep13: This looks very innocent and should be fine. I don't like merging broken PR's though. Would be nice to have the build fixed first.

**Comment by gep13** [comment]
@asbjornu see the convo in Gitter.  I suspect that the GitHub Rate Limit for GitReleaseNotes is kicking in.  Bottom line...  No PR's as the build script currently stands should work.  It is just a fluke that they are.

**Comment by pascalberger** [comment]
@gep13 I've merged #1058. Can you rebase this on current master so that the builds will pass

**Comment by gep13** [comment]
@pascalberger rebased. Thanks!

**Comment by pascalberger** [comment]
Thanks!

**Comment by asbjornu** [comment]
@gep13: Ah, brilliant! Thanks for this! ❤️

**Pull request merged**
