### PR TITLE
Remove obsolete config file

### PR DESCRIPTION
**Pull request by arturcic**
As the legacy configuration file was deprecated long time ago, I think in version 4.x we're removing it in this version

### CODE REVIEW

**Comment by asbjornu** [comment]
I think this change warrants a new major version. What do you think?

**Comment by arturcic** [comment]
Yeah, or it might be 5.2.0 as it's not breaking, it just removes the obsolete

**Comment by arturcic** [comment]
I was considering to change the milestone from 5.1.4 to 5.2.0 as there are a lot of issues/changes

**Comment by asbjornu** [comment]
Yeah, agreed. As you write, the deprecation warning has been there since v4, so let's bump to 5.2 and get rid of it.

**Pull request merged**
