### PR TITLE
Fix Variables link

### PR DESCRIPTION
**Pull request by robertlarkins**
The link to more-info/variables produced a 404 as it was missing .md.
This adds the .md extension to the link.

### CODE REVIEW

**Comment by gep13** [comment]
@robertlarkins thank you for taking the time to submit this, but this shouldn’t be required. I have just tested both of these links, and they work as expected for me, no 404’s.

Can you please confirm that you are still seeing a problem?

**Comment by arturcic** [comment]
@gep13  I can confirm it's working
https://gitversion.net/docs/build-server-support/build-server/azure-devops
I guess @robertlarkins  was targeting the old readthedocs site

**Comment by arturcic** [comment]
I guess we can close this one

**Comment by robertlarkins** [comment]
I followed the link while browsing md file in github (rather than the GitVersion site). But I'll retry from a desktop tomorrow to see if I can give the steps to recreate it.

**Comment by gep13** [comment]
>@robertlarkins said...
I followed the link while browsing md file in github (rather than the GitVersion site). But I'll retry from a desktop tomorrow to see if I can give the steps to recreate it.

Ah, that might explain it.

While the source md files are stored in GItHub, the intention is for the rendered content to be viewed here:

https://gitversion.net/docs/

**Comment by robertlarkins** [comment]
If you click either of the *variables* links from here: https://github.com/GitTools/GitVersion/blob/master/docs/input/docs/build-server-support/build-server/azure-devops.md
then you get a 404. But as there is no intention to view these docs through GitHub, then this is likely a non-issue, so I'll close it.

**Pull request closed without merging**
