### PR TITLE
Initial support of Drone

### LINKED ISSUE #1658: Support for Drone
It would be nice to add support for [Drone](https://drone.io/).

### PR DESCRIPTION
**Pull request by vhatsura**
The pull request add initial support of [Drone](https://drone.io/). to fix #1658

### CODE REVIEW

**Comment by vhatsura** [comment]
Hey, @arturcic!
Could you look into PR, please? It's important for us due to we cannot use git version with Drone in case build from pull request

**Comment by vhatsura** [comment]
@JakeGinnivan , @SimonCropp , can you look into this PR, please?

**Comment by SimonCropp** [comment]
@vhatsura sorry, i am no longer contributing to this project

**Comment by arturcic** [comment]
I guess adding Drone is a good addition, as it allows building on ARM chip. I guess we could also add support for building GitVersion on ARM as Libgit2Sharp is already adding supporting for ARM.

**Comment by arturcic** [comment]
@vhatsura thank you for you contribution! Do you mind checking how it works on Drone CI with the latest changes and give us feedback? And sorry it took so long.

**Comment by vhatsura** [comment]
@arturcic, sure. will check it. To be honest, GitVersion worked on Drone CI, however, during building PRs was some issues with branch identification.

**Comment by arturcic** [comment]
Now that the changes are merged hope it works as expected.

**Pull request merged**
