### PR TITLE
Fix addin/tool versions

### PR DESCRIPTION
**Pull request by gep13**
- This will make the builds more reliable and repeatable

### CODE REVIEW

**Comment by gep13** [comment]
@JakeGinnivan can you take a look at this?

**Comment by gep13** [comment]
@pascalberger yeah, that sounds like another bug that needs to be resolved.  I can try to take a look at that later, but can't guarantee it :-(

**Comment by JakeGinnivan** [comment]
Looks good to me, but we can't release beta13/14 yet. I have been testing and had scenarios where it isn't picking up merge messages, I think we have a decent regression somewhere

**Comment by gep13** [comment]
@JakeGinnivan ouch! Is this showing up in the tests, or just from your own testing?

**Comment by JakeGinnivan** [comment]
Just from my own testing. 

Also, there is a branch config inheritance issue.. See https://travis-ci.org/GitTools/GitVersion/jobs/312274320 - got stuck in a loop..

May take me a day or two, but I will try to add the tests and ensure we don't have those regressions.

It would be handy if everyone could build and do some basic testing of master on their own code bases to see if there are issues

**Comment by JakeGinnivan** [comment]
Hopefully this should go green now, then can merge and we should be good to release beta.14

**Comment by gep13** [comment]
@JakeGinnivan looks like there is still an issue with the uploading of artifacts.

**Comment by JakeGinnivan** [comment]
Odd that it's the branch build failing but all others succeed. I recon we just merge. It's probably a gem precondition not creating it for that build

**Pull request merged**
