### PR TITLE
test faulty test

### PR DESCRIPTION
**Pull request by casz**

### CODE REVIEW

**Comment by casz** [comment]
@asbjornu @arturcic seems `CleanupDuplicateOrigin` is causing havoc on Linux.

```
System.InvalidOperationException: Sequence contains no elements
    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
    at GitVersion.GitPreparer.CleanupDuplicateOrigin()
    at GitVersion.GitPreparer.Prepare(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes) in /home/vsts/work/1/s/src/GitVersionCore/GitPreparer.cs:line 62
    at GitVersion.GitVersionCalculator.CalculateVersionVariables() in /home/vsts/work/1/s/src/GitVersionCore/GitVersionCalculator.cs:line 51
    at GitVersion.ExecCommand.Execute() in /home/vsts/work/1/s/src/GitVersionExe/ExecCommand.cs:line 40
    at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments) in /home/vsts/work/1/s/src/GitVersionExe/GitVersionExecutor.cs:line 117
```

**Comment by casz** [comment]
There seems to be other errors as well
```
Error Message:
   System.InvalidOperationException : Sequence contains no matching element
  Stack Trace:
     at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at GitVersion.OutputVariables.VersionVariables.<>c__DisplayClass131_0.<FromDictionary>b__0(ParameterInfo p) in /home/vsts/work/1/s/src/GitVersionCore/OutputVariables/VersionVariables.cs:line 145
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at GitVersion.OutputVariables.VersionVariables.FromDictionary(IEnumerable`1 properties) in /home/vsts/work/1/s/src/GitVersionCore/OutputVariables/VersionVariables.cs:line 144
   at GitVersionExe.Tests.PullRequestInTeamCityTest.GivenARemoteWithATagOnMasterAndAPullRequestWithTwoCommitsAndBuildIsRunningInTeamCityVersionIsCalculatedProperly(String pullRequestRef) in /home/vsts/work/1/s/src/GitVersionExe.Tests/PullRequestInTeamCityTest.cs:line 47
```

I suspect that some environmental thing has changed or that is simple fails to create repos?

**Comment by asbjornu** [comment]
Thanks for debugging this, @casz. Perhaps it's possible to ignore errors that occur during the cleanup tasks altogether?

**Comment by casz** [comment]
I don't know the code base well enough to judge that 😓

**Comment by casz** [comment]
Seems to be fixed in master

**Pull request closed without merging**
