### PR TITLE
Fix #2412 - Initialized IgnoreConfig is now empty

### LINKED ISSUE #2412: [Bug] - GitVersion.yml - ignore part ignored
Gitversion does not take _ignore_ part of GitVersion.yml into account.

## Expected Behavior
We should be able to see _ignore_ settings of GitVersion.yml by running command `gitversion /showconfig`

## Actual Behavior
`gitversion /showconfig` shows default values for _ignore_ section in GitVersion 5.3.7. (I tested on 5.0.1 and everything was OK)

```
ignore:
  sha: []
```

## Steps to Reproduce
```
git init

git commit -m "initial" --allow-empty

cat GitVersion.yml
mode: Mainline
branches: {}
ignore:
  sha: [794454f56b4e7a1867b15bc3834d7169ed01b752]
merge-message-formats: {}

gitversion /showconfig
```
contains:
```
ignore:
  sha: []
```
but should contain:
```
ignore:
  sha:
  - 794454f56b4e7a1867b15bc3834d7169ed01b752
```

## Your Environment
- Version Used: 5.3.7+Branch.master.Sha.b22e8726683a0997484b53c5efd54394e93b5306
- Operating System and version : Windows 10.0.18362.0
- GitVersion installed by: choco install GitVersion.Portable

### PR DESCRIPTION
**Pull request by mirecad**
## Description
New empty instance of IgnoreConfig was wrongly marked as non empty. 

## Related Issue

Fixes #2412 

## Motivation and Context
Configuration wrongly marked as non empty overrides other configurations. We override user config with new empty instance of Config in ConfigProvider. This caused, that ignore part of user config was lost.

## How Has This Been Tested?
I added unit test: `/src/GitVersionCore.Tests/Model/IgnoreConfigTests.cs`

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by asbjornu** [comment]
Thanks for this, @mirecad! But can you please have a look at the failing tests?

**Comment by mirecad** [comment]
I just checked tests. The problem is, that default GitVersion.yml now contains line `is-empty: true`. Is this OK? I will modify test or serialization based on the answer.

```
next-version: 2.0.0
branches: {}
ignore:
  sha: []
  is-empty: true
merge-message-formats: {}
```

**Comment by asbjornu** [comment]
It doesn't make much sense to have `is-empty` as a configuration property, so please see to it that it isn't used in de/serialization.

**Comment by asbjornu** [comment]
Great! Another thing, do you think you can move the test alongside the other `ignore` tests?

https://github.com/GitTools/GitVersion/blob/d326a8822531d1a0990d73dd68f48d9d026c0c63/src/GitVersionCore.Tests/Configuration/IgnoreConfigTests.cs#L14-L48

**Comment by mirecad** [comment]
Sure. Test was moved.

**Review by arturcic — APPROVED** [review]

**Comment by odalet** [comment]
Just bumped into this very problem and was about to create a new issue suggesting this exact fix!

**Pull request merged**
