### PR TITLE
TfsTask - Add 'path' parameter

### PR DESCRIPTION
**Pull request by Rora**
Resolves issue #1401

### CODE REVIEW

**Comment by asbjornu** [comment]
@Rora, thanks for this. Is it possible to test this in any way? If so, could you please add a test, rebase and resolve conflicts? 🙏

**Comment by arturcic** [comment]
As far as I remember, this is a nodejs app so the only way to test it is by running as nodejs app. Not sure we can include a unit test

**Comment by asbjornu** [comment]
I don't mind having a test suite executed with `npm test`. If that's the only way to test this, then I would appreciate if we got something like that up and running.

**Comment by Rora** [comment]
I agree that it would be best to get a test suite up and running to be able to test this code. We should IMO log this as a separate issue as I don't have any experience in setting a nodejs test suite up and it would unnecessary prolong this PR.

**Comment by arturcic** [comment]
+1 for a separate PR

**Comment by asbjornu** [comment]
While I agree on doing a test suite as a separate PR, I would have preferred it the other way around; test suite first, features second. But seeing how long this PR has waited, I think it's fine merging this first.

**Pull request closed without merging**
