### PR TITLE
Updated to newer pre-release of libgitsharp to see if that could fix …

### PR DESCRIPTION
**Pull request by mkoertgen**
…#720

cf. https://github.com/GitTools/GitVersion/issues/720#issuecomment-238532783

### CODE REVIEW

**Comment by asbjornu** [comment]
@mkoertgen Thanks for this! But it seems like you haven't compiled or run the tests locally? Either way, this seems to be the problem causing Travis and AppVeyor to fail:

```c#
Mocks/MockQueryableCommitLog.cs(6,14): error CS0535: `MockQueryableCommitLog' does not implement interface member `LibGit2Sharp.IQueryableCommitLog.QueryBy(string, LibGit2Sharp.CommitFilter)'
/home/travis/build/GitTools/GitVersion/src/GitVersionCore.Tests/../packages/LibGit2Sharp.0.23.0-pre20160803182831/lib/net40/LibGit2Sharp.dll (Location of the symbol related to previous error)
Mocks/MockRepository.cs(5,14): error CS0535: `MockRepository' does not implement interface member `LibGit2Sharp.IRepository.Checkout(LibGit2Sharp.Tree, System.Collections.Generic.IEnumerable<string>, LibGit2Sharp.CheckoutOptions)'
```

**Comment by mkoertgen** [comment]
Oops, sorry about that. I did not think about breaking changes in libgitsharp.

**Comment by mkoertgen** [comment]
Added new implementations (with `throw new NotImplementedException()`. 3 tests are failing in teamCity-something. Will look into this.

**Comment by mkoertgen** [comment]
It looks as if some non-json output is prepended during the `PullRequestInTeamCityTest` fixture. This breaks the test because `result.OutputVariables` cannot be evaluated & asserted anymore.

Probably libgit2 now adds some more output...

**Comment by mkoertgen** [comment]
The test `JsonOutputOnBuildServer.BeingOnBuildServerDoesntOverrideOutputJson()` is still green. It verifies we get json output in teamcity-mode.

It seems that something in the libgit2 checkout commands add some ouput (Debug + Release).

**Comment by mkoertgen** [comment]
Tests still failing. Could make the test pass by just stripping output but i am pretty sure that's not what you want. @asbjornu, any guidance on this?

**Comment by asbjornu** [comment]
@mkoertgen The problem is that the following is written to `stdout` before the JSON, right?

```
revparsing refs/heads/pull/5/merge
grabbed ref refs/heads/pull/5/merge, obj 596f42dde6bd0be7ee2c462d50b095552c370c4d
grabbed branch refs/heads/pull/5/merge
branch: refs/heads/pull/5/merge
```

Since this problem started after upgrading LibGit2Sharp, am I right to assume that it is LibGit2Sharp that writes this to `stdout`? If so, we should redirect the output from LibGit2Sharp and only output anything from it if GitVersion's output is not JSON and/or there are errors where debug information from LibGit2Sharp could be useful.

**Comment by asbjornu** [comment]
@mkoertgen Yep, my assumption was correct. @JakeGinnivan [found this](https://github.com/libgit2/libgit2sharp/blob/500cc965dfb85806677c2c061e277e3a988b340a/LibGit2Sharp/Commands/Checkout.cs#L43). I'm sure it's a mistake that LibGit2Sharp would happily merge, given a pull request. Would you be up for providing a PR to LibGit2Sharp for removing those writelines?

**Comment by mkoertgen** [comment]
Thx for tracing that back. Seems already done https://github.com/libgit2/libgit2sharp/pull/1361

**Comment by asbjornu** [comment]
@mkoertgen Excellent, now we only need to wait for a new `.nupkg`. I hope they release one soon! :smiley:

**Comment by mkoertgen** [comment]
I updated libgit2sharp. However, that seemed to break 2 other tests

**Comment by mkoertgen** [comment]
Too bad. The release-note task fails for some reason, cf.: [4.0.0-PullRequest1024.1133.build.1055#L1035](https://ci.appveyor.com/project/GitTools/gitversion/build/4.0.0-PullRequest1024.1133.build.1055#L1035)

**Comment by JakeGinnivan** [comment]
@mkoertgen just re-triggered it, worked fine.

**Comment by mkoertgen** [comment]
Appveyor build succeeded, as well as the travis-ci build on linux. But for the osx-build one test failed. Probably the test is fragile?

**Comment by mkoertgen** [comment]
Still one test failing on the travis-build:

https://travis-ci.org/GitTools/GitVersion/jobs/166709203#L2277

**Comment by asbjornu** [comment]
@mkoertgen: Yeah, I'm sorry about that. I was hoping GitTools/GitTools.Core#38 would remedy [what you saw](https://travis-ci.org/GitTools/GitVersion/jobs/166709203#L2278) in #720, but this looks like a new problem. It might be related, so getting GitTools/GitTools.Core#38 merged, out the door and updated in GitVersion is worth a shot anyway.

We're unfortunately kind of stuck without @JakeGinnivan helping to release the packages, because the release process isn't fully automated in all the GitTools repositories yet and it's also not (fully) documented. Sorry! 😞

**Comment by asbjornu** [comment]
I've restarted the job in hope that the problem is transient.

**Comment by JakeGinnivan** [comment]
I have updated all the things on master. I will get a new v4 beta out today, let me know how it goes

**Pull request closed without merging**
