### PR TITLE
#3352 - Prevent version increment of versions from tracked release branches

### PR DESCRIPTION
**Pull request by rkieslinger**
Implements #3352

### CODE REVIEW

**Comment by arturcic** [comment]
@rkieslinger please rebase your PR on top of current state of `main`

**Comment by arturcic** [comment]
@HHobeck can you check if this PR still makes sense, otherwise please close it

**Comment by HHobeck** [comment]
> @HHobeck can you check if this PR still makes sense, otherwise please close it

Hi @arturcic.

I think this PR would not break anything and the feature request gives some options which might be useful. Anyway this PR is not done because of warnings and the line 86 in BaseVersionCalculators/TrackReleaseBranchesVersionStrategy.cs is not right implemented because the logic of branch inheritance is not considered correct:

```csharp
var currentBranchConfiguration = Context.GetEffectiveConfiguration(Context.CurrentBranch);
```

**Comment by arturcic** [comment]
> > @HHobeck can you check if this PR still makes sense, otherwise please close it
> 
> Hi @arturcic.
> 
> I think this PR would not break anything and the feature request gives some options which might be useful. Anyway this PR is not done because of warnings and the line 86 in BaseVersionCalculators/TrackReleaseBranchesVersionStrategy.cs is not right implemented because the logic of branch inheritance is not considered correct:
> 
> ```cs
> var currentBranchConfiguration = Context.GetEffectiveConfiguration(Context.CurrentBranch);
> ```

@HHobeck do you think you can take this one over and finalize it?

**Comment by HHobeck** [comment]
> > > @HHobeck can you check if this PR still makes sense, otherwise please close it
> > 
> > 
> > Hi @arturcic.
> > I think this PR would not break anything and the feature request gives some options which might be useful. Anyway this PR is not done because of warnings and the line 86 in BaseVersionCalculators/TrackReleaseBranchesVersionStrategy.cs is not right implemented because the logic of branch inheritance is not considered correct:
> > ```cs
> > var currentBranchConfiguration = Context.GetEffectiveConfiguration(Context.CurrentBranch);
> > ```
> 
> @HHobeck do you think you can take this one over and finalize it?

@rkieslinger: Hi Roland. Are you following this thread? If so can you please help to finalize this feature request!? Thank you.

**Comment by rkieslinger** [comment]
Hi! Sorry for the late response. We actually don't really need this feature anymore, status quo is ok for us. If nobody else needs it, we could delete this PR?

**Comment by arturcic** [comment]
Closing this PR

**Pull request closed without merging**
