### PR TITLE
Document variable usage change needed by 5.2.0

### PR DESCRIPTION
**Pull request by phatcher**

### CODE REVIEW

**Comment by asbjornu** [comment]
Is this still required in 5.2.1?

**Comment by arturcic** [comment]
I will release version 5.2.2 that will contain a fix, we might just change this PR to include both options to output the variables

**Comment by phatcher** [comment]
If it's fixed in 5.2.2, then I'll update the documentation to note that if you need to access the variables across jobs, then you need the extended syntax

**Comment by arturcic** [comment]
> If it's fixed in 5.2.2, then I'll update the documentation to note that if you need to access the variables across jobs, then you need the extended syntax

Version 5.2.2 was released and it seems it has fixed the issue, can you update your PR and include both type of usages? Thanks

**Comment by phatcher** [comment]
Sure will do

**Comment by arturcic** [comment]
@phatcher any updates on this one?

**Comment by phatcher** [comment]
I'll finish it off tonight

**Comment by arturcic** [comment]
just don't forget to rebase on top of master

**Pull request closed without merging**
