### PR TITLE
Add diag switch

### PR DESCRIPTION
**Pull request by JakeGinnivan**

### CODE REVIEW

**Comment by pascalberger** [comment]
LGTM. Maybe it would make sense to call /diag in the VSTS task if system.verbose variable is set (at least if it runs under the new agent where Git should be available)

**Comment by asbjornu** [comment]
Perhaps something similar can be done in GitVersionTask?

**Comment by JakeGinnivan** [comment]
@pascalberger @asbjornu am unsure about how to add this into GitVersionTask. I think having the CLI to diagnose issues is ok?

**Comment by gep13** [comment]
@JakeGinnivan agreed

**Comment by asbjornu** [comment]
Hm. Since [Visual Studio has a setting for MSBuild verbosity](http://stackoverflow.com/questions/1211841/how-can-i-make-visual-studios-build-be-very-verbose#1211886) and MSBuild itself has the `/verbosity:level` switch, you'd think this was something that could be detected somehow. Propagating that into GitVersionTask would be the ideal thing to do, imho.

**Pull request merged**
