### PR TITLE
Adds trouble shooting info for #1627

### PR DESCRIPTION
**Pull request by rominator1983**
## Description
Adds trouble shooting information for the case discussed in https://github.com/GitTools/GitVersion/issues/1627

## Related Issue
https://github.com/GitTools/GitVersion/issues/1627

## Motivation and Context
Get more information when this case happens

## How Has This Been Tested?
Unit tests have been run. It is not clear how this scenario can be created so it's not possible at the moment to create a unit test

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation. => no
- [x] I have updated the documentation accordingly. => no
- [x] I have added tests to cover my changes. => no. See above
- [x] All new and existing tests passed. => yes

### CODE REVIEW

**Comment by asbjornu** [comment]
I can't really see why the build is failing – I can't find the test that fails. Are you able to locate it?

**Comment by rominator1983** [comment]
I don't think that there are really single tests that fail. There are complete configurations like MacOS that fail while most configurations just work. I can check later.

Can you run the build on the current main? I think that this won't work either at the moment.

**Comment by arturcic** [comment]
I noticed the build recently got pretty unstable, especially the macOs agents, seems like there were some build agents updates that might affect the stability of the build, for now re-run of the failed jobs helps (sometimes couple of reruns)

**Comment by rominator1983** [comment]
Yeah tell me about it. We experience the same in other repositories. I think you restarted the checks? Thanks for that.

**Review by arturcic — APPROVED** [review]

**Pull request merged**
