### PR TITLE
Added Infinite loop protection

### PR DESCRIPTION
**Pull request by scphantm**
I added recursion breakout if it goes 50 levels deep

### CODE REVIEW

**Comment by scphantm** [comment]
addresses #2864

**Comment by scphantm** [comment]
My dev machine is a Mac so I'm unable to run .net6 in either rider or VStudioMac yet.  Since the code was already refactored for net6, i had to checkout the 5.7.0 tag and apply my changes there.  Thats the latest version i was able to run on my machine.  Someone with Windows is going to have to resolve the merge conflicts as i can't run that code at all.

**Comment by scphantm** [comment]
you are going to have to fix whatever is wrong.  its well beyond me until rider releases .net6 support which they said they won't until .net6 goes GA

**Comment by arturcic** [comment]
@scphantm I can understand that. I will see if we can find some time to check the changes you've done.
One thing to note though is you can have multiple .net sdk installed on a PC, and you can control which one is used for a specific project using global.json -> that means you can have .net 6 rc2 installed side by side with those sdk you already have for the other projects. Second thing. I use Jetrains ToolBox and am able to install the Rider version that I work for other projects that does not support .net6 (same as you have), and side by side I installed the EAP version that does support .net 6. So it's possible

**Review by mrt-135 — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
