### PR TITLE
Fixed typo in image reference commit id

### PR DESCRIPTION
**Pull request by sivarajans**
## Description
There was a typo in commit id reference in document

### CODE REVIEW

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@sivarajans wow! That is a great find! Thanks for catching that!

**Comment by asbjornu** [comment]
I think this is something we should do for v5, so I tried changing the base branch from `main` to `support/5.x`, but that of course needs a proper rebase. Are you able to do that @sivarajans? If not, I'll cherry-pick 248b901a95fef4f24f25347d997dc94d69201157 into a new PR.

**Comment by sivarajans** [comment]
> I think this is something we should do for v5, so I tried changing the base branch from `main` to `support/5.x`, but that of course needs a proper rebase. Are you able to do that @sivarajans? If not, I'll cherry-pick 248b901a95fef4f24f25347d997dc94d69201157 into a new PR.

Please cherry pick. Thank you

**Comment by sivarajans** [comment]
@asbjornu I have updated to feed this change to support/5.x branch.

**Comment by asbjornu** [comment]
@sivarajans, awesome! Thanks! 🙏🏼

**Pull request merged**
