### PR TITLE
GH-2127 - allow json and buildserver output at the same time

### LINKED ISSUE #1236: "/output json" does not work in build server environment
Hello

We would like to execute GitVersion from withing a build script, but would like to get the json output. If the build environment is detected, the option json is ignored.

This was already issued once: https://github.com/GitTools/GitVersion/issues/675 

Apparentely, this bug seems to be still open.

You can repro it by yourself by executing the following inside a PowerShell session:
```
$env:TF_BUILD = "True"
GitVersion.exe /output json /nofetch
```

The output is still the "buildserver" one.

### LINKED ISSUE #2127: Allow specifying -output json and -output buildserver at the same time
Might be a continuation of #1236

### PR DESCRIPTION
**Pull request by arturcic**
Closes #2127 Closes #1236

### CODE REVIEW

**Comment by arturcic** [comment]
> What happens if you duplicate `-output json`, for instance?

We use ISet, that means only one instance will be saved.


> Also, it's now impossible to **not** output JSON, true?

We add by default in the constructor of `Arguments` the json because we need to preserve the way it worked before

**Comment by arturcic** [comment]
But **not** using json at all, I think the old behavior allowed that. Let me check

**Comment by arturcic** [comment]
@asbjornu now it's possible to add only `-output buildserver` without `output json` as well as multiple times `-output json`  or `-output buildserver` or a combination of those

**Comment by gep13** [comment]
Interesting! This will help with one of the long time issues with using GitVersion and Cake on CI system. Namely that you would have to run GitVersion twice, once to set the BuildServer version and then again to get the asserted variables to use in rest of script.

**Comment by arturcic** [comment]
> Interesting! This will help with one of the long time issues with using GitVersion and Cake on CI system. Namely that you would have to run GitVersion twice, once to set the BuildServer version and then again to get the asserted variables to use in rest of script.

Right, that was one of the reasons I implemented this, to avoid running twice.

**Comment by arturcic** [comment]
@gep13 I think this change will break cake alias for GitVersion, am I right?

**Comment by gep13** [comment]
Off the top of my head, I am not sure. I would need to check. Travelling at the minute, so not in a position to look at this just now.

**Comment by arturcic** [comment]
@gep13 I think this will still work with the cake aliases, just whoever uses the cake aliases will not be able to specify both the `json` and `buildserver` output. So I think we can merge this. @asbjornu ?

**Comment by asbjornu** [comment]
Sure. But just to be clear: This closes #1236 and probably makes #983 obsolete as well, no? Writing the console output to a file is just `> GitVersion.json` in most console environments.

**Comment by asbjornu** [comment]
Unless we use the implementation of #983 to fix #1031. 🤔

**Comment by arturcic** [comment]
I think it will close #1236, 
As for #983  just > GitVersion.json might work except when the tool fails it will write to error to the GitVersion.json file so I'd prefer a new output instead.
As for #1031 it might partially fix the issue as we will only call it once instead of twice, making it less probable, but in the case of GitVersionTask it might occur as for each task it calls the GitVersion (something to refactor I think)

**Comment by asbjornu** [comment]
Good analysis. Please add `Closes #1236` in your PR description so it gets closed automatically on merge and then just merge ahead. :shipit

**Pull request merged**
