### PR TITLE
Docker naming scheme

### PR DESCRIPTION
**Pull request by arturcic**
Implements #1572 

I have already migrated the old images from the gittools/gitversion-dotnetcore and gittools/gitversion-fullfx to gittools/gitversion and adapted the tag names to use the new scheme

### CODE REVIEW

**Comment by arturcic** [comment]
In the `README.md` I have formatted the table of the artifacts, so now there is only one link to dockerhub, previously there were 2.

You should `Hide whitespace changes` in the Diff Settings when code reviewing

**Comment by asbjornu** [comment]
I see. I also did not understand the removal of the Travis badge, but I notice it has stopped reporting builds. Any idea why?

**Comment by arturcic** [comment]
There is some issue building with Travis for the last month, for Linux image most often, and because on Azure Pipelines we also use the linux and macos VMs I decided to disable building on Travis. The second reason for disabling Travis was it takes much longer to build with it as it first needs to install mono, and it usually takes ~60% of the build time. And from the point of view of Azure pipeline I have one configuration for all 3 OSes (and later planning to add the validation Docker jobs as well).

**Comment by arturcic** [comment]
Still I kept the travis configuration in code, in case we need to go back with Travis

**Comment by asbjornu** [comment]
Well, with [this](https://twitter.com/asbjornu/status/1098873841273708544) in mind, I think it's wise to move away from Travis altogether, I was just wondering. Azure Pipelines sure seems like a great solution. 👍

**Comment by arturcic** [comment]
We're using Azure Pipelines here for Gitversion for half a year already I guess, and it seems to work properly, especially in the context of Docker building

**Comment by arturcic** [comment]
Hey @asbjornu , do you think we can already merge this PR?

**Comment by asbjornu** [comment]
405c7008ad45472097ec80b4a6812ef4776a7c9e caused the [Windows build on Azure DevOps to ](https://dev.azure.com/GitTools/GitVersion/_build/results?buildId=240) to fail:

```
Executing: "C:/Program Files/Docker/docker.exe" build --build-arg "contentFolder=/content" --file "src/Docker/windows/windowservercore/net472/Dockerfile" --rm --tag "gittools/gitversion:5.0.0-windows-windowservercore-net472" --tag "gittools/gitversion:5.0.0-beta1-79-windows-windowservercore-net472" src/Docker/windows/windowservercore/net472
unable to prepare context: unable to evaluate symlinks in Dockerfile path: GetFileAttributesEx D:\a\1\s\src\Docker\windows\windowservercore\net472\Dockerfile: The system cannot find the file specified.
An error occurred when executing task 'Docker-Build'.
```

A bit strange that the build was successful in the PR, but not on `master`. Ideas, @arturcic?

**Comment by arturcic** [comment]
When there is a PR we don't run publish Docker, that calls Docker Build, that's why it did not fail. The issue was the misspelling of the distro, fixed in another commit

**Comment by asbjornu** [comment]
Aha, excellent.

**Comment by pauldotknopf** [comment]
Did the you guys delete docker images?

```manifest for gittools/gitversion:v4.0.0-beta.12 not found```

**Comment by arturcic** [comment]
I guess we did when migrating from other repositories. Can you use the 4.0.0 tag instead?

**Comment by pauldotknopf** [comment]
Is 4.0.0 still mono?

**Comment by arturcic** [comment]
You can use 4.0.0-linux-debian-net472, as this one is on top of mono image, the other netcoreapp is for dotnetcore

**Pull request merged**
