### PR TITLE
(GH-1932) Convert to Wyam for Documentation

### PR DESCRIPTION
**Pull request by gep13**
Still lots of work to do here, but thought I would get started...

### CODE REVIEW

**Comment by gep13** [comment]
Progress being made...

image

**Comment by gep13** [comment]
@arturcic @asbjornu @admiringworm would you all be able to take this branch for a spin, and provide some feedback on the current status of the conversion to Wyam?

Here is the main page:

image

You should be able to run the docs locally by running:

```
.\build.ps1 -Target Preview-Documenation
```

**Comment by arturcic** [comment]
@gep13 the links in the docs, do not work, they are pointing to *.md files, but if I remove the md in the url they work

Have a look here for example http://localhost:5080/GitVersion/docs/usage/usage

**Comment by gep13** [comment]
@arturcic I have updated the pages with the correct links.  Can you have another look at this?

**Comment by arturcic** [comment]
I'll have a look

**Comment by arturcic** [comment]
Looks great!! So I think we can merge it. @asbjornu thoughts? Btw @gep13  how will we host/deploy the new docs? How do you do it for GRM?

**Comment by gep13** [comment]
@arturcic I was planning on hosting this on GitHub Pages. I still have another task to add to the Wyam.cake file which would do that, but I wanted to check that everyone was happy with what I have before taking that step.

**Comment by arturcic** [comment]
> @arturcic I was planning on hosting this on GitHub Pages. I still have another task to add to the Wyam.cake file which would do that, but I wanted to check that everyone was happy with what I have before taking that step.

Go for it!

**Comment by asbjornu** [comment]
I'd like to set this up with https://gitversion.net/ as a custom URL once it's done. GitHub Pages would be perfect. 👌

**Comment by arturcic** [comment]
I merged it, let's give it a try

**Pull request merged**
