### PR TITLE
Docker documentation (v5)

### PR DESCRIPTION
**Pull request by asbjornu**
## Description
Add documentation for Docker usage (rebased version of #3858).

## Motivation and Context
It's currently not documented how to use GitVersion through Docker.

## How Has This Been Tested?
I've executed the docs build locally.

## Screenshots (if appropriate):
Docker usage documentation

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by arturcic** [comment]
@asbjornu because the v5.x branch is readonly I think the docs will get updated with the v6 release if you don't mind.

Overwise we can manually call the publish of the docs if we want to have the changes published earlier.

What do you think?

**Comment by asbjornu** [comment]
@arturcic, yeah. I was unsure about that. I think this is worth getting in. Is the docs publishing already possible to invoke manually, so it's not a lot of work?

**Comment by arturcic** [comment]
Yes, it should be possible

**Comment by asbjornu** [comment]
Cool, do you approve of the changes otherwise?

**Comment by arturcic** [comment]
I will check tomorrow the best option to publish the changes

**Comment by arturcic** [comment]
@asbjornu I manually published from v5 https://gitversion.net/docs/usage/docker so I will close this PR

**Pull request closed without merging**
