### PR TITLE
LibGit2Sharp update to 0.26.0 (2)

### PR DESCRIPTION
**Pull request by arturcic**
This is the re-implementation of #1659

### CODE REVIEW

**Comment by arturcic** [comment]
Currently we test the windows docker images and the linux .net core images, the mono images are not tested (as the 0.26.0 version of Libgi2sharp does not work properly with mono). I have some progress on testing the other artifacts - the nuget packages, but a PR is not ready yet. 

For testing the nuget packages (and probably the gem and vsix) I'll use some docker images - the debian/ubuntu/alpine will be the official images from microsoft, for fedora/centos custom base images. I'll create a separate repo under GitTools organization where the base images will be defined, and we'll use these images for testing the artifacts as well as as base images for the docker images we release with gitversion.

**Comment by asbjornu** [comment]
Sounds great, @arturcic. I really appreciate the amount of work you put into this!

**Comment by martin-pritchard** [comment]
Thanks for your efforts @arturcic - really looking forward to getting our hands on this! Are you able to merge the code, and push out to the nuget.org feed too please?

**Comment by arturcic** [comment]
> Thanks for your efforts @arturcic - really looking forward to getting our hands on this! Are you able to merge the code, and push out to the nuget.org feed too please?

I prefer not to merge my PRs; and I want to add nuget packaging testing inside docker images, to test the packages from this PR. It could be part of this PR or of another PR.

**Comment by asbjornu** [comment]
I've merged this now as it provides enough value in and of itself. But another PR with NuGet packaging testing inside the Docker images would be really sweet!

**Comment by arturcic** [comment]
@asbjornu, [this](https://github.com/GitTools/build-images) is the repo with the base docker images I'll use in an upcoming PR for testing the packages and for docker images we deliver

**Comment by martin-pritchard** [comment]
Thanks all - that works a treat!
Version in nuget.org for anyone that's watching: 5.0.0-beta3-44

**Comment by asbjornu** [comment]
Thanks for the information, @martin-pritchard. I'm glad it works.

**Comment by arturcic** [comment]
I guess we need to validate it works for other bugs related to libgit2sharp version

**Comment by EwanNoble** [comment]
Looks like this has resolved a lot of issues! Is there any chance of getting the latest netcore build pushed to the task on Azure DevOps for further testing?

**Comment by arturcic** [comment]
That's on my list before release the 5.0.0 version

**Comment by EwanNoble** [comment]
> That's on my list before we release the 5.0.0 version

Fantastic, will keep an eye out for it

**Pull request merged**
