### PR TITLE
Working Travis build

### PR DESCRIPTION
**Pull request by asbjornu**
This PR completes the Mono support started in #816 and contains fixes all over the place to achieve a [working build on Travis](https://travis-ci.org/asbjornu/GitVersion). Most tests are executed and succeed, but some tests using the `ShouldMatchApproved()` extension method from Shouldly had to be ignored, since they fail due to missing source information.

If Shouldly gains Mono `.mdb` symbol support, these tests can be un-ignored and the Travis (Linux) build of GitVersion should be on par with Windows and we should be in a great place to ensure Unix, Linux and Mono compatibility going forward.

After merging this, a Travis build badge like this can be added to the README:

[Build Status](https://travis-ci.org/asbjornu/GitVersion)

### CODE REVIEW

**Comment by asbjornu** [comment]
Hm, why isn't AppVeyor building this, by the way?

**Comment by gep13** [comment]
@asbjornu good question.  @JakeGinnivan any ideas?

**Comment by asbjornu** [comment]
@gep13 My guess is that since the branch `feature/mono-support` was merged in f4795ffaf656335efba0f71f13702f56bfa6364f and this PR is based off of the same branch, AppVeyor believes that no build is required. I can create a new branch to create a new PR from, perhaps?

**Comment by asbjornu** [comment]
Closing in favor of #856, which is being built by AppVeyor right this moment.

**Pull request closed without merging**
