### PR TITLE
Added back vanquished 'n'

### PR DESCRIPTION
**Pull request by asbjornu**
Added back 'n' that got vanquished in 7965dd76fc32db27f029e0a6879e6254ef724409

### CODE REVIEW

**Comment by gep13** [comment]
@asbjornu I actually just noticed this, and committed directly into master 😄

**Comment by asbjornu** [comment]
@gep13 Ah, ok. Thanks! 😄

**Comment by gep13** [comment]
Probably should have PR'ed it as well, but since it was a little change, I thought I would it put it straight in 😸

**Comment by asbjornu** [comment]
Haha, no problem!

**Pull request closed without merging**
