### PR TITLE
Conditional ms build tasks

### PR DESCRIPTION
**Pull request by pi3k14**
Added a possibility to conditionaly omit/avoid Targets in the GitVersionTask.targets file. As default all task are enabled (no change in default behavior).
If user eg. set property UpdateAssemblyInfo to false, this task won't be executed.

### CODE REVIEW

**Comment by gep13** [comment]
@SimonCropp does this look ok to you?  Thanks!

**Comment by JakeGinnivan** [comment]
Can you add these additional properties to the docs?

**Comment by SimonCropp** [comment]
@gep13 looks ok to me

**Comment by JakeGinnivan** [comment]
Just checking on the status of this. @pi3k14 are you able to update the docs in this PR then I can merge it in?

**Comment by pi3k14** [comment]
Hm, I got some merge problem when trying to update the documentation, and some more strange results when trying to sync my repo with GitVersion repo. Did someone remove the docs/usage.md?

Everything seems OK now (from my perspective :)

**Comment by JakeGinnivan** [comment]
Someone did move usage actually. it got split up into usage for the different ways. If you have time you can rebase and apply the changes to the correct file. Otherwise I will do it myself when I have a chance

**Comment by pascalberger** [comment]
Usage.md is now split into multiple files here: https://github.com/GitTools/GitVersion/tree/master/docs/usage. Your changes should go into https://github.com/GitTools/GitVersion/blob/master/docs/usage/msbuild-task.md

**Comment by pi3k14** [comment]
Ah, OK - will take a stab at it.

**Comment by pi3k14** [comment]
Argh, git is not my tool. 
The files are OK, but the commit history is terrible.

**Comment by pascalberger** [comment]
You can squash todays commits together to make the commit history look nicer

**Comment by gep13** [comment]
@pi3k14 if you are not familiar with how to do this, here are a couple articles that might help you:

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

Feel free to ask if you run into any problems.  Rewriting commit history can be daunting to start with, but after you have done it a couple times, it becomes very easy :smile_cat:

**Comment by pi3k14** [comment]
Thanks for the information, I read that squash/rebase has to be done before push'ing to another repo?

Have I misunderstood something?

**Comment by pascalberger** [comment]
Squashing and rebasing rewrites history, which is a bad thing if you have pushed the branch and someone else has cloned the repo and checked out your branch. But in the case of this PR I think it won't be a problem to rewrite history, since you can assume that no one else has cloned from your repo.

**Comment by gep13** [comment]
Exactly what @pascalberger said :+1:  Also, it is why we recommend that all work be done in a branch off of master, so that we have the opportunity to allow squashing and rewriting.  It is something that should be used with caution, but it is also something that is incredibly powerful once you are comfortable using it.

**Comment by pi3k14** [comment]
Nah, throwing in the towel (my local repo is a complete mess, and files in PR is wrong).
Closing the PR and creating a new one

**Pull request closed without merging**
