### PR TITLE
Mode and configuration documentation cleanup

### PR DESCRIPTION
**Pull request by asbjornu**
This PR should fix a dead link from `configuration.md` to `versioning-mode.md`, moves the latter file into the `reference` folder, consolidates its content with the different mode files and cleans up all related files in many various ways that I hope should improve this part of the documentation. I have no idea how this looks and works on ReadTheDocs, but fingers crossed this doesn't break anything!

### CODE REVIEW

**Comment by gep13** [comment]
@asbjornu @JakeGinnivan is there a way to run readthedocs locally to test how it works before pushing?

**Comment by JakeGinnivan** [comment]
Yeah, install mkdocs locally, then run `mkdocs serve`

**Comment by JakeGinnivan** [comment]
http://www.mkdocs.org/#installation

**Comment by asbjornu** [comment]
@JakeGinnivan Thanks for the tip. I clicked through the documentation locally and found a bug plus a better way to organize the versioning modes. I've also rebased the PR.

**Comment by gep13** [comment]
@JakeGinnivan thanks! I have it up and running locally now as well (after a little fighting with python and pip)

**Comment by asbjornu** [comment]
@JakeGinnivan I added a test in 9cf8c30259a851f1751991e1259332f0a21a0964 to ensure that all documentation files exist in the index. Through that, I found one that wasn't (`git-branching-strategies/gitflow-examples_complete.md`) and added that in 1e0ccfb9e20f305d0830d3d270fc49d08dabcad1.

**Comment by JakeGinnivan** [comment]
@asbjornu that is awesome!

**Pull request merged**
