### PR TITLE
Guess when there are two branches pointing at the same commit. Trying…

### PR DESCRIPTION
**Pull request by JakeGinnivan**
… to go for most stable branch

Still cases where it will fail build, but this should fix the most common cases

@distantcam this was the issue you mentioned at .net usergroup. Am struggling to think of other ways to fix it, ideas welcome

### CODE REVIEW

**Comment by distantcam** [comment]
The scenario I was describing was when using GitFlow, and the head of master has a tag, GitVersion keeps crashing when trying to build from that commit.

**Comment by JakeGinnivan** [comment]
Ah, recon you could put together a test for that fail?

**Comment by gep13** [comment]
Is this related to the same problem that I had the other day?

Situation:

* Using GitFlow
* Just finished a bunch of work on the develop branch
* Create a release branch off develop
* Immediately do a pull request into master branch (i.e. no additional commits in the release branch)
* GitVersion complains

Thoughts?

**Comment by JakeGinnivan** [comment]
Probably, where it says it can't figure out which branch to run on?

**Comment by gep13** [comment]
Yes, which results in the error message that I linked to here:

https://twitter.com/gep13/status/619532094226755584

**Comment by JakeGinnivan** [comment]
Think that one is different. Will try to put a test together replicating that on this PR and fix it also

**Comment by JakeGinnivan** [comment]
Probably quite related though

**Comment by JakeGinnivan** [comment]
@gep13 having trouble reproducing that issue in a test. Thoughts?

**Comment by gep13** [comment]
Hmmm, nothing springing to mind :-(

**Comment by JakeGinnivan** [comment]
@gep13 gonna merge this, can you pull down the latest code and reproduce the issue you had. I now dump the commit log to the log so we can create the test which reproduces.

**Comment by gep13** [comment]
@JakeGinnivan are you creating a new beta and pushing to chocolatey?  If so, I can test pretty much straight away by running build on AppVeyor, otherwise, I will need to manually add compiled exe into repo.

**Comment by JakeGinnivan** [comment]
If you target the PR to GitVersion, it dogfoods itself, so it is always using latest

**Comment by JakeGinnivan** [comment]
I was probably just going to release stable next

**Comment by gep13** [comment]
>@JakeGinnivan said...
If you target the PR to GitVersion, it dogfoods itself, so it is always using latest

Hmmm, not sure how I would simulate the exact steps though.  Would need:

* a develop branch
* do some commits on that
* create release branch
* PR into master (with no additional commits on develop)

Seems like a lot of things to do on a repo that isn't set up to do GitFlow.  Happy to do those changes, if you are happy for me to give it a try.

**Comment by JakeGinnivan** [comment]
Maybe we can just push v3 then sort it in a patch release?

**Comment by JakeGinnivan** [comment]
Anything from your side which would stop the v3 release?

**Comment by gep13** [comment]
>@JakeGinnivan said...
Anything from your side which would stop the v3 release?

Not that I can think of, no.  Would be happy to see this released, the beta (expect from this one issue on the release PR) has been working fine for me for a while now.

**Pull request merged**
