### PR TITLE
Implemented Release notes publishing

### PR DESCRIPTION
**Pull request by arturcic**
Implements #1493

### CODE REVIEW

**Comment by gep13** [comment]
@arturcic I applaud your choice of tool here 👍

**Comment by arturcic** [comment]
Now you know the reason I did the PRs for GitReleaseManager

**Comment by arturcic** [comment]
@gep13 the build succeed. Do you mind merging this PR?

**Comment by gep13** [comment]
@arturcic your changes have been merged, thanks for your contribution 👍

**Pull request merged**
