### PR TITLE
Upgrade LibGit2Sharp to 0.26.0

### PR DESCRIPTION
**Pull request by asbjornu**
Upgrade LibGit2Sharp from version `0.25.0-preview-0033` to version `0.26.0`.

### CODE REVIEW

**Comment by arturcic** [comment]
Hey @asbjornu what about the nuspec? there are several nuspec that we use for generating the nuget packages. We need to update that as well. Still the newer version of Libgit2sharp has different layout of the dependencies that we need to check (I mean the way it resolves the RID for different distros). That's why I postponed updating Libgit2sharp for now.

**Comment by asbjornu** [comment]
Good point, @arturcic. And as expected, the build failed. I just wanted to try it out in order to address the comments in #1483.

**Comment by arturcic** [comment]
It's on my todo list tp update to latest libgit2sharp and fix the packaging. I hope to find some time for that

**Comment by trondhindenes** [comment]
it would be awesome to have this fixed. We have to keep old build agents and build on old container images (based on Ubuntu 16) in order for gitversion to work.

**Comment by bmargula** [comment]
Yes, GitVersion Task V4 on Azure DevOps always fails when using the Microsoft hosted Ubuntu 1604 based agent. Please update this as soon as possible

**Pull request closed without merging**
