### PR TITLE
Make sure that we're not evaluating excluded branches

### PR DESCRIPTION
**Pull request by orjan**
This pull request addresses issue #684

### CODE REVIEW

**Comment by orjan** [comment]
In https://github.com/GitTools/GitVersion/pull/673 I noticed that `track-merge-target` must be set to track `develop` is develop is merged into `master` but then, getting the base configuration got really slow on the build server e.g.

```
feature[/-]:
    track-merge-target: true
```

```
[20:31:40][Step 1/1] INFO [10/08/15 20:30:56:35] Project root is: D:\BuildAgent\work\607b08944775ee0f
[20:31:40][Step 1/1] INFO [10/08/15 20:30:56:45] Using latest commit on specified branch
[20:31:40][Step 1/1] INFO [10/08/15 20:30:56:46] Begin: Attempting to inherit branch configuration from parent branch
[20:31:40][Step 1/1]   INFO [10/08/15 20:30:56:46] Begin: Finding branch source
[20:31:41][Step 1/1]   INFO [10/08/15 20:30:56:68] End: Finding branch source (Took: 217.25ms)
[20:34:53][Step 1/1]   INFO [10/08/15 20:34:09:30] Found possible parent branches: develop, origin/develop, origin/feature/BRIKKS-4556-spider
[20:34:53][Step 1/1]   WARN [10/08/15 20:34:09:30] Failed to inherit Increment branch configuration, ended up with: develop, origin/develop, origin/feature/BRIKKS-4556-spider
[20:34:53][Step 1/1] 
[20:34:53][Step 1/1] Falling back to develop branch config
[20:34:53][Step 1/1] INFO [10/08/15 20:34:09:30] End: Attempting to inherit branch configuration from parent branch (Took: 192,845.07ms)
[20:34:53][Step 1/1] INFO [10/08/15 20:34:09:32] Running against branch: feature/BRIKKS-4569 (e9b0fbfec6d781af8ebd47e478cdcef036fb69e3)
[20:34:53][Step 1/1] INFO [10/08/15 20:34:09:33] Begin: Calculating base versions
```

This my first attempt to address this performance bottleneck and all feedback is welcome.

image

**Comment by JakeGinnivan** [comment]
Did you see my comment on the cause in the other thread?

Sent from my Windows Phone
________________________________

**Comment by orjan** [comment]
If you are referring to removing the commit message strategy, so yes? I think this pr addresses something else, e.g the last yellow line in the trace here: https://github.com/GitTools/GitVersion/pull/677#issuecomment-146864984

I think it's 2 different execution paths, both suffering performance problems?

**Comment by orjan** [comment]
Dot trace after the optimization:

image

**Pull request merged**
