### PR TITLE
Feature/630 create assembly info

### PR DESCRIPTION
**Pull request by Philo**
#re 630

### CODE REVIEW

**Comment by gep13** [comment]
@Philo looks like there are some issues with the CI Build as a result of the changes that you have made.  Are you in a position to look into what is going on?

Thanks!

**Comment by Philo** [comment]
@gep13, I'll take a look, however may not be today

**Comment by gep13** [comment]
@Philo not a problem at all :+1:

**Comment by Philo** [comment]
@gep13 - fixed the build now

**Comment by gep13** [comment]
@Philo thanks for your contribution here! :+1:

**Comment by JakeGinnivan** [comment]
I think this has a bug in it.

It should only add the assembly info attributes in if the filename is specified. I think this is the cause of the assembly info issues since the last release

**Pull request merged**
