### PR TITLE
Fix   dotnet publish  and VS2017  

### PR DESCRIPTION
**Pull request by maikebing**
ILRepack is removed. 
dotnet publish  can publish you dotnet core  projects !

### CODE REVIEW

**Comment by maikebing** [comment]
@asbjornu    @gep13   @pascalberger   can you review it and  merge  or talk about this pr ?

**Comment by asbjornu** [comment]
Are we dogfooding or testing the changes that are made here in any way?

**Comment by maikebing** [comment]
I compile and use it in a production environment and it seems to be fine at the moment.

**Comment by asbjornu** [comment]
@maikebing: What I meant was: Is GitVersion using the result in the build so if you actually broke something in this PR, we would notice it?

**Comment by asbjornu** [comment]
@dazinator: Can you please take a look at this and whether it's something we want to merge? Aren't you dealing with many of the same issues in #1269?

**Comment by maikebing** [comment]
@asbjornu   
Here's what to note: 
1, ILRepack can not be a good combination of. Net Core dependencies, so abolished it.
2, except VS2017 I did not test in other versions of VS.

**Comment by maikebing** [comment]
If there is any question and need me to do, please tell me, I hope to do better.   
@asbjornu

**Comment by dazinator** [comment]
Yeah this is covered in the netstandard pr, along with the other dotnet cli commands (restore, build, pack, etc). If its possible hold off merging this one then it will result in an easier merge of that other PR (less conflicts to resolve) whenever that happens.

**Comment by dazinator** [comment]
Closing this as the latest `netstandard` PR should have addressed this, please comment if not.

**Pull request closed without merging**
