### PR TITLE
Add BuildKite build agent

### LINKED ISSUE #2956: [Feature] Add Buildkite build agent
GitVersion should be able to use Buildkite environment variables to detect the current branch rather than doing some extra checkouts to get out of a detached HEAD state.

## Detailed Description

Add a new Buildkite class that extends the `BuildAgentBase` class. This would allow GitVersion to work more seamlessly when running on a Buildkite agent. Implementation would roughly be:
- `CanApplyToCurrentContext()` would check that the `$BUILDKITE` environment variable is set to `true`
- `GetCurrentBranch()` would return the value that the `BUILDKITE_BRANCH` environment variable is set to

c.f. [Buildkite Environment Variables](https://buildkite.com/docs/pipelines/environment-variables)

Could also be nice to have GitVersion set version info via [Buildkite's meta-data](https://buildkite.com/docs/agent/v3/cli-meta-data) - but I'm not sure how good of an idea it is to have GitVersion exec another process...Besides you can always just call it yourself somewhere in your build pipeline like so:

```shell
buildkite-agent meta-data set "GitVersion_SemVer" $(gitversion -showvariable SemVer)
```

## Context

By default a Buildkite agent checks out a branch in detached HEAD state. It's possible to work around it via doing this at start of every build:

```
git checkout $BUILDKITE_BRANCH
git reset HEAD --hard $BUILDKITE_COMMIT
```

Would be nice for GitVersion to automatically detect the branch name via the built-in `$BUILDKITE_BRANCH` environment variable.

## Possible Implementation

Have a branch ready to PR here: https://github.com/aidenhaak/GitVersion/commit/f9492d64e76bc532b0ff5737590cca12257aee4d 🙂

### PR DESCRIPTION
**Pull request by aidenhaak**
## Description
Added a Buildkite build agent so that GitVersion can use the `BUILDKITE_BRANCH` environment variable when running on a Buildkite agent.

## Related Issue

Resolves #2956.

## Motivation and Context
By default Buildkite checkout a branch in a headless state. This change removes the need for adding this at the start of a Buildkite pipeline:
```shell
git checkout $BUILDKITE_BRANCH
git reset HEAD --hard $BUILDKITE_COMMIT
```
## How Has This Been Tested?
- Added unit tests
- Manually tested in a Buildkite pipeline

Please note I wasn't able to check my added documentation is valid as I got this error trying to run the build script:
```
❯ .\build.ps1 -Target Preview-Documentation
Running build stage build...

Tool Codecov.Tool is already installed, with required version.
Tool GitVersion.Tool is already installed, with required version.
Error: The target 'Preview-Documentation' was not found.
```
## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by aidenhaak** [comment]
Not sure what's going on with the documentation part of the build...any ideas @asbjornu ?

**Comment by asbjornu** [comment]
@aidenhaak, good question. There's nothing in this PR that should cause the "Could not find module `remark-frontmatter`" failure. Ideas @arturcic?

**Comment by arturcic** [comment]
@asbjornu it seems it's the [Remark Linting] step in the docs that are failing. If I remember correctly that was added by you some time ago as part of the docs validation. Can you check that?

**Comment by asbjornu** [comment]
Yeah, I noticed that. I just can't think of a reason for it to suddenly stop working. I'll have a look.

**Review by asbjornu — CHANGES_REQUESTED** [review]
@aidenhaak, the build is now successful, but there are a few nitpicks pointed out by Reviewdog that would be great if you could fix. 🙏🏼

**Comment by aidenhaak** [comment]
@asbjornu fixed! Worth squashing `1a2bd5a` and `925ff8c` together?

**Review by asbjornu — APPROVED** [review]
@aidenhaak, awesome! No squashing needed. :)

**Pull request merged**
