### PR TITLE
Git version calculating wrong version when building a tag

### LINKED ISSUE #2074: [BUG] GitVersion calculating wrong version when building a tag
I am running GitVersion 5.1.3 on Windows Server 2019 connecting to BitBucket Cloud, and using TeamCity and its GitVersion metarunner to generate version numbers.

With a particular GitFlow repo that I have, I am building on `support/12.4` and everything is great, GitVersion calculates the version number as e.g. 12.4.11-beta0003. However, when I tag that commit which I have just built as e.g. 12.4.12, then GitVersion completely ignores that tag and grabs the version number from `develop`, giving me a tag something like 13.4.0-tags-12-4-11.1+8.

It only does this on the build agent; when I run GitVersion on my desktop then it calculates the version correctly.

### PR DESCRIPTION
**Pull request by gerwinjansen**
Note: this PR is on top of #2411, that's why you see the changes again.

## Description
TaggedCommitVersionStrategy will try to return the tags on the current commit. If there are none, it will returns the tags from the history.

## Related Issue
Fixes #2074 GitVersion calculating wrong version when building a tag

## How Has This Been Tested?
See steps to reproduce in my comments of the related ticket.

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by asbjornu** [comment]
This is great! But there's something odd going on with the [Docker tests](https://github.com/GitTools/GitVersion/pull/2413/checks?check_run_id=1206594999#step:7:169). Can you please look into that?

```
========================================
Docker-Test
========================================
Executing task: Docker-Test
Testing image: gittools/gitversion:5.4.0-linux-alpine.3.10-x64-netcoreapp2.1
Output : 5.4.0-PullRequest2413.140
An error occurred when executing task 'Docker-Test'.

----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Starting Teardown...
Repository info : IsMainRepo True, IsMainBranch False, IsTagged: False, IsPullRequest: True
Finished running tasks.
Error: One or more errors occurred. (Assert.Equal() Failure
                                 ↓ (pos 23)
Expected: ···.0-PullRequest2413.171
Actual:   ···.0-PullRequest2413.140
                                 ↑ (pos 23))
	Assert.Equal() Failure
                                 ↓ (pos 23)
Expected: ···.0-PullRequest2413.171
Actual:   ···.0-PullRequest2413.140
                                 ↑ (pos 23)
Error: Process completed with exit code 1.
```

**Comment by gerwinjansen** [comment]
I have no clue how to run the docker tests locally and debug them.
Can you help me out?

**Comment by asbjornu** [comment]
Can you provide some guidance, @arturcic?

**Comment by asbjornu** [comment]
Can you please rebase on the `HEAD` of `master` and resolve conflicts, @gerwinjansen?

**Comment by gerwinjansen** [comment]
@asbjornu: build is succesful (without any changes from my side). Can this PR be completed now?

**Review by asbjornu — APPROVED** [review]

**Comment by asbjornu** [comment]
Excellent, thank you so much for your contribution @gerwinjansen! 🙏

**Pull request merged**
