### PR TITLE
Support generating F# AssemblyVersion attributes

### PR DESCRIPTION
**Pull request by jpierson**
Partially addresses issue #138

### CODE REVIEW

**Comment by jpierson** [comment]
Any thoughts on this failed build for Mono? I'm not familiar with Travis CI but it looks like some merge prior to my pull request may have broken some environment configuration.

**Comment by asbjornu** [comment]
@jpierson: Good question. The build has been failing for quite a while and I haven't been able to pinpoint exactly which commit broke it in the way it is failing now. Sigh.

**Comment by jpierson** [comment]
@asbjornu At this point is the automated build failure the only thing holding up this pull request. Getting this F# support is important to a project I'm supporting.

**Comment by jpierson** [comment]
Looking at the build history it looks like [this build](https://travis-ci.org/GitTools/GitVersion/builds/203414858) may be suspect as the first time the failures started.

**Comment by asbjornu** [comment]
@jpierson: Since the build succeeds on AppVeyor, I'll merge this. But the build you point to can't really be at blame, since it's firstly a merge **from** `master` to another branch and secondly only [contains changes to the documentation](https://github.com/GitTools/GitVersion/commit/0e3a5d3e5fae80f493b249c7388e9e526c3a8949).

**Pull request merged**
