### PR TITLE
Ensure IEquatable takes nullable type

### PR DESCRIPTION
**Pull request by Evangelink**
Ensure that `IEquatable<T>` targets nullable type and update related implementation.

## Related Issue

Follow-up of #2765

### CODE REVIEW

**Review by asbjornu — COMMENTED** [review]
Can you please provide a bit more context and information regarding this change? I hoped we would get fewer `?` in the codebase going forward, not more?

**Comment by Evangelink** [comment]
I just assumed that as we were doing null checks in the equals, it was better to explicitly allow nulls but I understand your point. We can probably close the PR.

**Comment by asbjornu** [comment]
Ok, I see. I suppose it's difficult to ensure these types aren't `null` earlier in the codebase?

**Comment by Evangelink** [comment]
At this point yes. I assume/hope it will be easier after a couple of null-check iterations :)

**Comment by asbjornu** [comment]
Indeed, let's merge this then. Can you please rebase and resolve conflicts?

**Comment by Evangelink** [comment]
@asbjornu Done.

**Review by asbjornu — APPROVED** [review]

**Pull request merged**
