### PR TITLE
Fall back to `master` if `main` is missing

### LINKED ISSUE #2590: [Bug] 5.6.5 Not finding Tag in master repo
My master branch has a Tag 6.1.0.
It get correctly picked up by version 5.6.4 

```
  INFO [01/28/21 13:53:18:60] Begin: Calculating base versions
    INFO [01/28/21 13:53:18:62] Fallback base version: 0.1.0 with commit count source 1f34f7b0477ebdaba3db9de21c9bc4aa1ba432d9
    INFO [01/28/21 13:53:18:67] Git tag '6.1.0': 6.1.0 with commit count source ee2c143847ae685ad96dedb7020bf563ac535bea
    INFO [01/28/21 13:53:18:72] Found multiple base versions which will produce the same SemVer (6.2.0), taking oldest source for commit counting (Git tag '6.1.0')
    INFO [01/28/21 13:53:18:72] Base version used: Git tag '6.1.0': 6.1.0 with commit count source ee2c143847ae685ad96dedb7020bf563ac535bea
  INFO [01/28/21 13:53:18:72] End: Calculating base versions (Took: 117.57ms)
```

but in version 5.6.5 it is not found:

```
INFO [02/09/21 7:24:04:69] Begin: Calculating base versions
    INFO [02/09/21 7:24:04:71] Fallback base version: 0.1.0 with commit count source 1f34f7b0477ebdaba3db9de21c9bc4aa1ba432d9
    INFO [02/09/21 7:24:04:80] Found multiple base versions which will produce the same SemVer (0.2.0), taking oldest source for commit counting (Fallback base version)
    INFO [02/09/21 7:24:04:80] Base version used: Fallback base version: 0.1.0 with commit count source 1f34f7b0477ebdaba3db9de21c9bc4aa1ba432d9
  INFO [02/09/21 7:24:04:80] End: Calculating base versions (Took: 118.04ms)
```

### PR DESCRIPTION
**Pull request by asbjornu**
Fall back to `master` if `main` is missing.

## Description
Since the default branch was changed from `master` to `main` in #2573, some scenarios have stopped working as explained in #2590. This PR attempts to fix that by falling back to `master` if `main` is missing. Hopefully, this shouldn't break any existing tests. 

## Related Issue
Fixes #2590.

## Motivation and Context
The change introduced in #2573 wasn't meant to be breaking, so we should do what we can to remedy any breaking it may have lead to.

## How Has This Been Tested?
I haven't written any tests for this yet. I'm not sure how to reproduce it, so if all tests are still green I think this should be merged even without a regression test.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by asbjornu** [comment]
Thinking more about this, why aren't we using the configured branch name regex for the main branch? The main branch could be `foobar` without breaking, imho.

**Comment by arturcic** [comment]
Usually these test are failing for the build agents because the environment variables are not properly reset

**Comment by arturcic** [comment]
> Are the environment variables not reset between different builds, or within the same build? If it's within the same build, is the problem related to parallelization? Can we make the tests execute serially to ensure a proper cleanup between each test execution?

It needs more investigation

**Comment by asbjornu** [comment]
Seems like the problem was the following line attempting to resolve `Lazy<GitVersionContext>.Value` in `TrackReleaseBranchesVersionStrategy.ctor`:

https://github.com/GitTools/GitVersion/blob/9c7e71372caf2dfcb6e975b74bcd6db085595415/src/GitVersion.Core/VersionCalculation/BaseVersionCalculators/TrackReleaseBranchesVersionStrategy.cs#L38

I've fixed this now by resolving the configuration more lazily inside the `MainTagsVersions` method and will cherry-pick and push the rest of the commits which I hope will also stay green. 🤞🏼

**Review by arturcic — APPROVED** [review]

**Pull request merged**
