### PR TITLE
Update mainline.md

### PR DESCRIPTION
**Pull request by zammitjohn**
As of v6.0.0 of the schema, the Mainline mode and the related implementation has been removed completely. The new Mainline version strategy should be used instead.

## Description

As per new version on the schema, we must use the new strategies array.

## Motivation and Context

Fixes to documentation.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by HHobeck** [comment]
I would recommend the following configuration when using the Mainline strategy:

1. From scratch:
```yaml
workflow: ''
strategies:
- Mainline
- ConfiguredNextVersion
...
```

2. Using the pre-defined `GitFlow` workflow as a base template:
```yaml
workflow: GitFlow/v1
strategies:
- Mainline
- ConfiguredNextVersion
```

3. Using the pre-defined `GitHubFlow` workflow as a base template:
```yaml
workflow: GitHubFlow/v1
strategies:
- Mainline
- ConfiguredNextVersion
```

4. Using the pre-defined `TrunkBased` workflow as a base template:
```yaml
workflow: TrunkBased/preview1
strategies:
- Mainline
- ConfiguredNextVersion
```

We need to make clear that it is a new implementation which needs to be used in experimental context only. In advance multi mainline branches are not supported in version 6.x.
- #4057

**Comment by arturcic** [comment]
@HHobeck can we merge this one? The build will not continue as there are only documentation changes

**Comment by HHobeck** [comment]
> @HHobeck can we merge this one? The build will not continue as there are only documentation changes

Actually I would like to see the points I mentioned in the documentation. The current change makes no sense because it lean on the fact that the default value of workflow is `GitFlow/v1` (This is because of backwards compatibility reason). In future releases we are going to no support this.

**Comment by arturcic** [comment]
> > @HHobeck can we merge this one? The build will not continue as there are only documentation changes
> 
> Actually I would like to see the points I mentioned in the documentation. The current change makes no sense because it lean on the fact that the default value of workflow is `GitFlow/v1` (This is because of backwards compatibility reason). In future releases we are going to not support this (probably).

Can we update the docs based on your suggestion and then we can push the rc2?

**Comment by HHobeck** [comment]
> Can we update the docs based on your suggestion and then we can push the rc2?

Yes I agree

**Comment by arturcic** [comment]
@HHobeck please then close this PR

**Pull request closed without merging**
