### PR TITLE
GH-2255 - implemented Commandline and Portable validation

### LINKED ISSUE #2255: [Improvement] Validate GitVersion.Commandline and GitVersion.Portable artifacts
Validate GitVersion.Commandline and GitVersion.Portable artifacts during Artifacts test stage to avoid having empty packages

### PR DESCRIPTION
**Pull request by arturcic**
Resolves #2255

### CODE REVIEW

**Comment by gep13** [comment]
@arturcic thanks for the mention.  Was good to see how this was implemented!

**Comment by asbjornu** [comment]
Fantastic, @arturcic! 👏 ❤️

**Comment by arturcic** [comment]
> @arturcic thanks for the mention.  Was good to see how this was implemented!

You're welcome

**Comment by arturcic** [comment]
> Fantastic, @arturcic! 👏 ❤️ 

Thanks

**Pull request merged**
