### PR TITLE
Add readme to the docs directory

### PR DESCRIPTION
**Pull request by asbjornu**
This PR adds a `readme.md` file to the `docs` directory, to make it easier contributing to the documentation, serve the documentation up locally with `mkdocs serve`, etc.

### CODE REVIEW

**Comment by pascalberger** [comment]
Thanks @asbjornu! I would suggest that we also add links to the new readme to make it more discoverable. Eg to [CONTRIBUTING.md](https://github.com/GitTools/GitVersion/blob/master/CONTRIBUTING.md)

**Comment by asbjornu** [comment]
@pascalberger Good idea. Let me test a few ways of how it might best work. Potentially breaking commits incoming! :smile:

**Comment by asbjornu** [comment]
@pascalberger There, I think that looks ok. Thoughts?

**Comment by gep13** [comment]
LGTM! :+1:

**Pull request merged**
