### PR TITLE
GH-1883, fix the NoFetch for GitVersionTask

### PR DESCRIPTION
**Pull request by arturcic**
Fix for #1883

### CODE REVIEW

**Comment by casz** [comment]
@arturcic I'll build a nupkg locally and test the fix 😄

**Comment by arturcic** [comment]
Thanks, I was waiting for the build to finish before the merge

**Comment by arturcic** [comment]
And if you could confirm its working before the merge then it's even better

**Comment by casz** [comment]
I got side-tracked, checking now :D

**Comment by casz** [comment]
Passes on our Jenkins CI

**Comment by arturcic** [comment]
When version 5.1.2-beta.1+18 gets published can you try it and confirm again?

**Comment by casz** [comment]
Sure, no problem then I can also test dotnet tool :)

**Comment by arturcic** [comment]
@casz thanks btw for the quick feedback and the help you provided for finding the cause of the issue

**Pull request merged**
