### PR TITLE
Update version-increments.md

### PR DESCRIPTION
**Pull request by Wesley-Lomax**
Added space to examples for minor, patch and fix as required for the regex

### CODE REVIEW

**Comment by pascalberger** [comment]
Thanks for the PR!

I never used this feature, but shouldn't this also work without the whitespaces according to [this test case](https://github.com/GitTools/GitVersion/blob/da0cca830b9c56b3572d2c8ed5a58fd7a74871e3/src/GitVersionCore.Tests/IntegrationTests/VersionBumpingScenarios.cs#L36)? Anyone knows how this was intended to work?

Otherwise I would suggest to fix the code to allow whitespaces instead.

**Comment by asbjornu** [comment]
Since `+semver: breaking`, `+semver: major` and `+semver: feature` are with a space, it makes sense for consistency to add a space to `+semver:minor`, `+semver:patch` and `+semver:fix` as well. I do agree the code should allow both, though.

**Comment by Wesley-Lomax** [comment]
They are show with a space here as well  - https://gitversion.readthedocs.io/en/latest/configuration/

**Comment by JakeGinnivan** [comment]
It works for both looking at the regex: https://github.com/GitTools/GitVersion/blob/master/src/GitVersionCore/IncrementStrategyFinder.cs#L19

**Comment by JakeGinnivan** [comment]
Thanks!

**Pull request merged**
