### PR TITLE
Don't consider "tag-prefix" as optional if it's explicitly specified

### LINKED ISSUE #3216: [Improvement] Don't consider `tag-prefix` as optional
## Detailed Description

Currently `tag-prefix` is always considered as optional which makes calculation of the next version incorrect. It mixes prefixed and unprefixed versions and takes the largest of both.

## Context

To correctly calculate the next version with the prefix. For example, we develop the main product and some its plugin in the same repository and have the following git tags list:
- 0.1.0
- 0.1.1
- 0.2.0
- 0.2.1
- plugin_0.1.0
- plugin_0.1.1
The expected next plugin version is 0.1.2 not 0.2.2 (plugin_ prefix will be prepended before setting the tag).

### PR DESCRIPTION
**Pull request by AlexPykavy**
## Description

To correctly calculate the next version with the prefix.

For example, we develop the main product and some its plugin in the same repository and have the following git tags list:
- 0.1.0
- 0.1.1
- 0.2.0
- 0.2.1
- plugin_0.1.0
- plugin_0.1.1

The expected next plugin version is `0.1.2` not `0.2.2` (`plugin_` prefix will be prepended before setting the tag).

## Related Issue

Resolves #3216.

## Motivation and Context

Makes possible to have 2 independent versioning sequences in the same repository.

## How Has This Been Tested?

Unit test case is added.

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by asbjornu** [comment]
I'm not sure whether to consider this a breaking change or not. If it isn't, we should re-target and rebase it on `support/5.x` instead of `main` and ship it in a v5 minor release. Also please have a look at #3218 and #3060 which seems related.

**Comment by AlexPykavy** [comment]
@asbjornu , I've reviewed https://github.com/GitTools/GitVersion/issues/3218 (and the corresponding PR https://github.com/GitTools/GitVersion/pull/3224) and https://github.com/GitTools/GitVersion/issues/3060. I agree with https://github.com/GitTools/GitVersion/pull/3224#issuecomment-1277296403 answer that we are talking about different tags.

I think that the only reason why this change can be considered as a breaking if `gitversion init` command puts the default `tag-prefix`. I checked it and looks like it doesn't. Then, may I just retarget the PR if there are no other comments?

**Comment by asbjornu** [comment]
@AlexPykavy, yes, I think you can retarget this against `support/5.x`.

**Comment by AlexPykavy** [comment]
> @AlexPykavy, yes, I think you can retarget this against `support/5.x`.

Done.

**Pull request merged**
