### PR TITLE
Updated Dockerfile to build slim image

### PR DESCRIPTION
**Pull request by VEnis**
Base image is now just debian slim. 
Minimal required packages are installed.
Release is taken exactly from github releases (latest stable release used).
Size of the built image is just 222MB

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
This will break the docker image publish: https://github.com/GitTools/GitVersion/blob/3172ff93931d774ea1d56dad69788e220516930c/deploy.cake#L191

**Comment by JakeGinnivan** [comment]
The change itself looks good, if you can just change the source of the gitversion binary so release will still be automated

**Comment by arturcic** [comment]
@VEnis This was implemented as part of this PR #1485. Can you have a look at  [dotnetcore](https://hub.docker.com/r/gittools/gitversion-dotnetcore/) and close this PR? The linux image is based on microsoft/dotnet:2.1-runtime, that is based on debian:stretch-slim.

**Comment by arturcic** [comment]
Closing this as it was implemented in #1485

**Pull request closed without merging**
