### PR TITLE
Add unit test to investigate and hopefully verify #2454

### PR DESCRIPTION
**Pull request by senritsu**
## Description
Added a unit test for investigating branch versioning issues, as prompted by @asbjornu in the discussion of #2454.

## Related Issue
#2454

## Motivation and Context

The test was initially created to reproduce #2454. The test failed when it was initially created, but passes on current `main` (with some modifications to the version in the issue discussion). There are a few details that I am still not completely clear on:

- Should hotfix branches get a `beta` prerelease tag? In the new test they don't, but according to [this line in another test](https://github.com/senritsu/GitVersion/blob/48b0e9dadd97344aac3142dc5cdcb0f1f3a2a48c/src/GitVersion.Core.Tests/IntegrationTests/HotfixBranchScenarios.cs#L95) maybe they should?
- Build metadata does not appear, but that is probably because of the mode CD in the `Config` used?
- Some of the versioning in the different tests in the file seemed inconsistent when first writing the test, I did not have the time to fully check that this time around, so it could use some more scrutiny
- Some comments need to still be removed before the PR should be merged

Disregarding those details, it seems like #2454 is not an issue anymore (?).

## How Has This Been Tested?
The change is a unit test, it was executed

## Screenshots (if appropriate):
N/A
## Checklist:
- [x] My code follows the code style of this project.
- [ ] ~~My change requires a change to the documentation.~~
- [ ] ~~I have updated the documentation accordingly.~~
- [ ] ~~I have added tests to cover my changes.~~
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by asbjornu** [comment]
The tests are successful?

**Comment by senritsu** [comment]
Seems like it, yes. I made a few adjustments because apparently some things changed since the original discussion. 

Disregarding the few comments the test may actually validate that #2454 was unintentionally fixed in the meantime, but I would not hold my breath on it just yet.

**Comment by asbjornu** [comment]
The successful test may be a false positive as discovered in https://github.com/GitTools/GitVersion/pull/2830#issuecomment-918809996.

**Comment by asbjornu** [comment]
Can you please rebase against `main` to see whether the test is still successful?

**Comment by senritsu** [comment]
I can confirm that the test still passes, even with the current changes from `main`.

I am still unsure if a hotfix branch should have a `beta` prerelease tag, similar to a `release` branch. Currently it only has (with versioning mode CD) the same tag like `main`/`master`, `-ci.n`.

When that is clarified I would remove the corresponding comments from the unit test, and the test would seem to confirm that at least one scenario of #2454 appears to work now. Of course that only goes for `mode: ContinuousDeployment`, and there may be edge cases that are missing.

**Comment by senritsu** [comment]
Curiously, when trying out 5.7.0 with one of our internal library repositories, the hotfix branch *does* in fact get a `beta` tag, albeit without `mode: ContinuousDeployment`. 

This adds another datapoint and confirms that in at least one of our productive scenarios, #2454 now seems to be fixed.

**Comment by senritsu** [comment]
Probably an unrelated issue, but the same package that works perfectly fine now locally still fails to properly account for the hotfix on our buildserver (TeamCity). Locally it versions to `0.5.1`, on TC it ignores the hotfix and stays on `0.5.0`.

**Comment by senritsu** [comment]
Additional scenarios have been added to the test, both new tests now fail. In both modes the second hotfix is ignored for versioning purposes.

**Comment by asbjornu** [comment]
As the accompanying issue #2454 is closed with a workaround, is this PR relevant anymore?

**Comment by arturcic** [comment]
Closes in favor of #3445

**Pull request closed without merging**
