### PR TITLE
Add VersionSourceSha to output

### LINKED ISSUE #1607: Add VersionSourceSha to output
I think this can be useful.
On dev branch we use commits between BaseSha and Sha to collect issues from comments and setup fix version in jira.

This should be simple because MetaDataCalculator already contains base commit info. 
I can make pull request.

### PR DESCRIPTION
**Pull request by hayhay27**
VersionSourceSha is sha of baseVersionSource commit in MetadataCalculator

Resolves #1607.

### CODE REVIEW

**Comment by hayhay27** [comment]
> Looks good, but I'm missing at least one test specifically for `VersionSourceSha`. Think you can add one or more, @hayhay27?

I thought about special test but many cases covers by existing tests (truly for SemanticVersionBuildMetaData). I not found any test on MetaDataCalculator. I can make them for it and check VersionSourceSha. Other modified tests already check output variables against approved results. Including VersionSourceSha.

**Comment by hayhay27** [comment]
@asbjornu, I look forward to your approve.

**Comment by asbjornu** [comment]
Excellent, thanks for your contribution @hayhay27!

**Comment by hayhay27** [comment]
I'm glad, thanks.

**Pull request merged**
