### PR TITLE
Re-submission of PR for Issue#1429 - C++ Support

### PR DESCRIPTION
**Pull request by stunney**
Re-submitted PR for https://github.com/GitTools/GitVersion/issues/1429

### CODE REVIEW

**Comment by stunney** [comment]
@gep13 @asbjornu will anyone accept my merge request? :)

**Comment by gep13** [comment]
@stunney as I think has been mentioned elsewhere, there is a big PR/changes in the works just now to switch GitVersion to using .Net Standard.  That works is starting to look like it will be completed soon, at which point, I think we can start looking at other pieces of functionality as well.

**Comment by stunney** [comment]
Would this change be more readily welcome on the released branch as a patch instead of the master/4.0beta branch?

**Comment by gep13** [comment]
@stunney either would work, but I doubt that neither would be looked at until the current work of converting to .NET Standard, and getting the release process and handover work is completed.

**Comment by asbjornu** [comment]
@stunney: Do you have time and interest in rebasing this and resolving conflicts? I also see no tests in the PR, is that possible to add?

**Comment by asbjornu** [comment]
Closing due to inactivity. Just reopen with added tests if and when you have the time.

**Pull request closed without merging**
