### PR TITLE
Treat the local and remote branches as equal if they have the same name when inheriting configuration

### LINKED ISSUE #2419: Failed to inherit Increment branch configuration, ended up with <mybranch>, origin/<mybranch>
GitVersion is calculating the wrong version, when a parent branch exists both as local and remote branch.
In that case, it print this warning:
```
WARN [10/07/20 14:29:24:80] Failed to inherit Increment branch configuration, ended up with: support/v1.0.x, origin/support/v1.0.x
Falling back to develop branch config
```
The default Increment of the `develop` branch is Minor, whereas Patch is expected for the support branch.

## Steps to Reproduce
```
git init remote
cd remote
git commit --allow-empty -m "init"
git tag -a -m "Release 1.0" v1.0
git checkout -b develop
git commit --allow-empty -m "new feature"
git checkout master
git checkout -b support/v1.0.x
git commit --allow-empty -m "hotfix"
git tag -a -m "Release 1.0.1" v1.0.1

cd ..
git clone remote local
cd local
git checkout master
git checkout develop
git checkout support/v1.0.x
git checkout -b bugfix
git commit --allow-empty -m "bugfix"
```

## Expected Behavior
```
"FullSemVer":"1.0.2-bugfix.1+1"
```

## Actual Behavior
```
"FullSemVer":"1.1.0-bugfix.1+2"
```

## Solution direction
Treat the local and remote branches as equal if they have the same name

### PR DESCRIPTION
**Pull request by gerwinjansen**
## Description
Fixed this by distincting the branches that are used to inherit configuration by their name-without-remote.

## Related Issue
Fixes #2419

## Motivation and Context
GitVersion is calculating the wrong version, when a parent branch exists both as local and remote branch.

## How Has This Been Tested?
See steps to reproduce in the related issue.

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by RomanBadiornyi** [comment]
Hi @gerwinjansen,  

I'm getting the same issue as described in 2419. I was trying to play a bit with git configuration, re-define source branches etc. with no luck.
Do you know, do we have any workaround? 
Or only this fix can solve the issue?

**Comment by gerwinjansen** [comment]
If it is acceptable to you, you can set the same `Increment` policy for all branches.
Otherwise I'm not aware of any workaround.

**Comment by asbjornu** [comment]
@gerwinjansen, any chance to get this PR green somehow?

**Comment by Labouh** [comment]
This is a real bug, could you patch the official version of GitVersion ?

**Review by asbjornu — APPROVED** [review]

**Pull request merged**
