### PR TITLE
Gitlab CI support

### PR DESCRIPTION
**Pull request by dfyx**
I've added build server support for [GitLab CI](https://about.gitlab.com/gitlab-ci/). The implementation is just copied from the code for Jenkins with a few small changes to use the correct environment variables.

We've been using this in production with an MSBuild Task for a few weeks and it works great with no further configuration required.

### CODE REVIEW

**Comment by gep13** [comment]
@dfyx thanks for your contribution to GitVersion, it really is appreciated!  Just a couple questions...

I haven't played with GitLab CI, so please excuse my ignorance, is there a way to set the Build Number in GitLab?

**Comment by gep13** [comment]
@dfyx or anyway to set build parameters?

**Comment by dfyx** [comment]
GitLab CI allows build scripts to be arbitrary shell scripts (both bash and Windows Batch are supported), so you can just run GitVersion as the first step of your build and dump everything into normal environment variables like you would probably do on a development machine.

I haven't played around much with the GitVersion command line tools. Instead I've used the MSBuild task via a Nuget package (I install my patched version of the package through my company's private Nuget repository server). Without my patch it complained that it could not find the current branch name so I just adapted the script for Jenkins to read that out of the correct environment variable.

GitLab CI even sets some pretty useful variables on its own such as `CI_BUILD_ID`. More details can be found at http://doc.gitlab.com/ce/ci/variables/README.html

**Comment by dfyx** [comment]
ping

**Comment by dfyx** [comment]
@gep13 @JakeGinnivan Is there any more info you need to merge this? The code has been running on our build servers for weeks now and we didn't have a single problem.

**Comment by gep13** [comment]
@dfyx no, no further information I required, I, or Jake, just need to find the time to review properly, and merge into main branch.  Sorry for not looking at this, we really do appreciate your contribution!

**Comment by gep13** [comment]
@dfyx thanks again for your contribution to GitVersion, and apologies for the delay in getting this pulled in! :+1:

**Pull request merged**
