### PR TITLE
Adding support to generate WiX version files

### PR DESCRIPTION
**Pull request by ruhullahshah**
Will take up the pending work of PR (https://github.com/GitTools/GitVersion/pull/1386) here

### CODE REVIEW

**Comment by ruhullahshah** [comment]
@asbjornu  I have added the approval test.
Build on Linux & MacOS fail however.  Failed to parse arguments: /tmp/TestRepositories/a33c7f98-2ff5-4f0f-9ae9-34e49c184f41/ /updatewixversionfile /l /tmp/TestRepositories/a33c7f98-2ff5-4f0f-9ae9-34e49c184f41/log.txt
 
 Could not parse command line parameter '/tmp/TestRepositories/a33c7f98-2ff5-4f0f-9ae9-34e49c184f41/log.txt'.

Is this known?

**Comment by asbjornu** [comment]
@ruhullahshah, on non-Windows operating systems, the arguments needs to use dash (`-`), not slash (`/`) since slashes are interpreted as file paths.

**Comment by ruhullahshah** [comment]
@asbjornu I have converted the command line arguments, from the feature specific tests, to `-` instead of `/`. However, the tests still fail on MacOS & Linux, due to other arguments that are not added by the feature specific tests.

**Comment by ruhullahshah** [comment]
@asbjornu Any plans to merge this?

**Comment by asbjornu** [comment]
@ruhullahshah, yes, absolutely. But I'd like to get rid of all these merge commits. Do you think you can do a rebase of your PR branch against `HEAD` of `master` and then `push --force`?

**Comment by ruhullahshah** [comment]
@asbjornu Done

**Comment by asbjornu** [comment]
@ruhullahshah, awesome! Thanks.

**Pull request merged**
