### PR TITLE
Finalizing the configuration of GitFlow and GitHubFlow workflow and align with the Mainline version strategy

### PR DESCRIPTION
**Pull request by HHobeck**
Finalizing the configuration of GitFlow and GitHubFlow workflow and align with the Mainline version strategy

## Description
Do minor changes and refactoring of code

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by HHobeck** [comment]
I have done a supplement to the previous PR because of some minor changes. Please review it and give me feedback @asbjornu

**Comment by arturcic** [comment]
@HHobeck before merging this one we need to this the CI on `main` branch

**Comment by HHobeck** [comment]
> @HHobeck before merging this one we need to fix the CI on `main` branch

Yes I agree. Can you help me to fix this? I see the following error:

```
Error: Assert.Contains() Failure: Sub-string not found
String:    "6.0.0-PullRequest4020.1488"
Not found: "6.0.0-PullRequest4020.3535"
```

**Comment by HHobeck** [comment]
> > @HHobeck before merging this one we need to fix the CI on `main` branch
> 
> Yes I agree. Can you help me to fix this? I see the following error:
> 
> ```
> Error: Assert.Contains() Failure: Sub-string not found
> String:    "6.0.0-PullRequest4020.1488"
> Not found: "6.0.0-PullRequest4020.3535"
> ```

Maybe it has something to do with the following fix:
- https://github.com/GitTools/GitVersion/issues/2394

**Comment by HHobeck** [comment]
I think this PR can be merged. Do you have any suggestion for finalization?

**Comment by arturcic** [comment]
> I think this PR can be merged. Do you have any suggestion for finalization?

Nope, we need first to fix the main build before merging this one

**Comment by arturcic** [comment]
@HHobeck I sent you the details I found while investigating the build error

**Pull request merged**
