### PR TITLE
Added support for remote repositories (with and without authentication)

### PR DESCRIPTION
**Pull request by GeertvanHorrik**
When no local .git folder is available, it is now possible to execute the logic on remote branches:

gitversion -url [repositoryurl]

to use authentication:

gitversion -url [repositoryurl] -u [username] -p [password]

### CODE REVIEW

**Comment by dazinator** [comment]
Just wondering if this feature makes it possible to run team city builds without having to set "checkout on agent" ? Or am I getting the wrong end of the stick? 

By default, Team city is set to Automatically check out on the Server, and historically unless you change it to "agent" side checkouts, then there is no git directory. Does this solve this issue?

**Comment by GeertvanHorrik** [comment]
Yes, this feature solves that issue.

**Comment by dazinator** [comment]
Wowser that's brilliant. Any chance of someone who knows how this feature works, creating a simple wiki entry showing how to use server side checkout with team city and gitversion? I have historically used jake's blog entry: http://jake.ginnivan.net/blog/2014/07/09/my-typical-teamcity-build-setup/ but I think that only applies for agent checkouts.
The reason being is i'd love to switch back to server checkout asap.

**Comment by dazinator** [comment]
I have tried to configure this within Team City but authentication is failing.

I am trying to use an SSH Key to authenticate, rather than my github username and password. cAN You tell me if this is supported?

Here is how TeamCity is invoking GitVersion:

`
"G:\Program Files\TeamCity\buildAgent\work\2b1e52cf22ed9beb\lib\GitVersion.CommandLine.2.0.0\Tools\GitVersion.exe" /url https://github.com/dazinator/CrmAdo.git /u ******* /output buildserver /updateassemblyinfo true -assemblyVersionFormat MajorMinorPatch


Where the argument being passed in for /s is a SSH key on my github account listed here: https://github.com/settings/ssh

The error I get is:

`
[Step 1/5] Starting: "G:\Program Files\TeamCity\buildAgent\work\2b1e52cf22ed9beb\lib\GitVersion.CommandLine.2.0.0\Tools\GitVersion.exe" /url https://github.com/dazinator/CrmAdo.git /u ******* /output buildserver /updateassemblyinfo true -assemblyVersionFormat MajorMinorPatch
[20:43:46][Step 1/5] in directory: G:\Program Files\TeamCity\buildAgent\work\2b1e52cf22ed9beb
[20:43:47][Step 1/5] Retrieving git info from url 'https://github.com/dazinator/CrmAdo.git'
[20:43:47][Step 1/5] An unexpected error occurred:
[20:43:47][Step 1/5] System.NullReferenceException: Object reference not set to an instance of an object.
[20:43:47][Step 1/5]    at LibGit2Sharp.RemoteCallbacks.GitCredentialHandler(IntPtr& ptr, IntPtr cUrl, IntPtr usernameFromUrl, GitCredentialType credTypes, IntPtr payload)
[20:43:47][Step 1/5]    at LibGit2Sharp.Core.NativeMethods.git_clone(RepositorySafeHandle& repo, String origin_url, FilePath workdir_path, GitCloneOptions& opts)
[20:43:47][Step 1/5]    at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
[20:43:47][Step 1/5]    at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
[20:43:47][Step 1/5]    at GitVersion.GitPreparer.GetGitInfoFromUrl()
[20:43:47][Step 1/5]    at GitVersion.GitPreparer.Prepare()
[20:43:47][Step 1/5]    at GitVersion.Program.Run()
`

**Comment by nulltoken** [comment]
@dazinator GitVersion relies on LibGit2Sharp which doesn't support SSH yet. Feel free to subscribe to https://github.com/libgit2/libgit2sharp/pull/852 in order to gets notified about progress.

```
`
"G:\Program Files\TeamCity\buildAgent\work\2b1e52cf22ed9beb\lib\GitVersion.CommandLine.2.0.0\Tools\GitVersion.exe" /url https://github.com/dazinator/CrmAdo.git /u ******* /output buildserver /updateassemblyinfo true -assemblyVersionFormat MajorMinorPatch

Where the argument being passed in for /s is a SSH key on my github account listed here: https://github.com/settings/ssh

The error I get is:


[Step 1/5] Starting: "G:\Program Files\TeamCity\buildAgent\work\2b1e52cf22ed9beb\lib\GitVersion.CommandLine.2.0.0\Tools\GitVersion.exe" /url https://github.com/dazinator/CrmAdo.git /u ******* /output buildserver /updateassemblyinfo true -assemblyVersionFormat MajorMinorPatch
[20:43:46][Step 1/5] in directory: G:\Program Files\TeamCity\buildAgent\work\2b1e52cf22ed9beb
[20:43:47][Step 1/5] Retrieving git info from url 'https://github.com/dazinator/CrmAdo.git'
[20:43:47][Step 1/5] An unexpected error occurred:
[20:43:47][Step 1/5] System.NullReferenceException: Object reference not set to an instance of an object.
[20:43:47][Step 1/5] at LibGit2Sharp.RemoteCallbacks.GitCredentialHandler(IntPtr& ptr, IntPtr cUrl, IntPtr usernameFromUrl, GitCredentialType credTypes, IntPtr payload)
[20:43:47][Step 1/5] at LibGit2Sharp.Core.NativeMethods.git_clone(RepositorySafeHandle& repo, String origin_url, FilePath workdir_path, GitCloneOptions& opts)
[20:43:47][Step 1/5] at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
[20:43:47][Step 1/5] at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
[20:43:47][Step 1/5] at GitVersion.GitPreparer.GetGitInfoFromUrl()
[20:43:47][Step 1/5] at GitVersion.GitPreparer.Prepare()
[20:43:47][Step 1/5] at GitVersion.Program.Run()
```

Regarding the log above, it looks like only passing in the username causes an NullReferenceException which is... Hmmm... unfortunate.

The error may originate from **[here](https://github.com/ParticularLabs/GitVersion/blob/cba8b2b13e97ba536c1a02e0124f06a6b7c17ad8/GitVersionExe/GitPreparer.cs#L60)**. Either we should change this way of blindly building the callback or we should ensure that we do not accept partial credentials as parameters (eg. only the username is this case).

@SimonCropp @JakeGinnivan  Thoughts?

**Comment by dazinator** [comment]
Oh gees, was I only passing username. I thought I was passing username and password.. Dear lord. I will try it again. this time I'll try and pass in the actual arguments that I need to! :)

**Comment by dazinator** [comment]
@nulltoken - Sorry I am actually passing both username and password and I get the same exception.

Here is a new log:

```
Starting: "G:\Program Files\TeamCity\buildAgent\work\2b1e52cf22ed9beb\lib\GitVersion.CommandLine.2.0.0\Tools\GitVersion.exe" /url https://github.com/dazinator/CrmAdo.git /u dazinator /p ******* /output buildserver /updateassemblyinfo true -assemblyVersionFormat MajorMinorPatch
[21:40:11][Step 1/5] in directory: G:\Program Files\TeamCity\buildAgent\work\2b1e52cf22ed9beb
[21:40:11][Step 1/5] Deleting existing .git folder from 'G:\Program Files\TeamCity\buildAgent\work\2b1e52cf22ed9beb\_dynamicrepository\.git' to force new checkout from url
[21:40:11][Step 1/5] Setting up credentials using name 'dazinator'
[21:40:11][Step 1/5] Retrieving git info from url 'https://github.com/dazinator/CrmAdo.git'
[21:40:21][Step 1/5] Working directory: G:\Program Files\TeamCity\buildAgent\work\2b1e52cf22ed9beb\_dynamicrepository
[21:40:21][Step 1/5] Applicable build agent found: 'TeamCity'.
[21:40:21][Step 1/5] One remote found (origin -> 'https://github.com/dazinator/CrmAdo.git').
[21:40:21][Step 1/5] Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.
[21:40:22][Step 1/5] Creating local branch from remote tracking 'refs/remotes/origin/dev'.
[21:40:22][Step 1/5] Creating local branch from remote tracking 'refs/remotes/origin/gh-pages'.
[21:40:22][Step 1/5] Skipping local branch creation since it already exists 'refs/remotes/origin/master'.
[21:40:22][Step 1/5] HEAD points at branch 'refs/heads/master'.
[21:40:22][Step 1/5] Running against branch: master
[21:40:22][Step 1/5] GitHubFlow version strategy will be used
[21:40:22][Step 1/5] An unexpected error occurred:
[21:40:22][Step 1/5] System.ArgumentNullException: Value cannot be null.
[21:40:22][Step 1/5] Parameter name: path1
[21:40:22][Step 1/5]    at System.IO.Path.Combine(String path1, String path2)
[21:40:22][Step 1/5]    at GitVersion.NextVersionTxtFileFinder.TryGetNextVersion(SemanticVersion& semanticVersion) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\GitHubFlow\NextVersionTxtFileFinder.cs:line 19
[21:40:22][Step 1/5]    at GitVersion.NextSemverCalculator.<GetPossibleVersions>d__2.MoveNext() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\GitHubFlow\NextSemverCalculator.cs:line 53
[21:40:22][Step 1/5]    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
[21:40:22][Step 1/5]    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
[21:40:22][Step 1/5]    at GitVersion.NextSemverCalculator.NextVersion() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\GitHubFlow\NextSemverCalculator.cs:line 29
[21:40:22][Step 1/5]    at GitVersion.BuildNumberCalculator.GetBuildNumber(GitVersionContext context) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\GitHubFlow\BuildNumberCalculator.cs:line 22
[21:40:22][Step 1/5]    at GitVersion.Program.Run()
```

**Comment by dazinator** [comment]
I will try and debug this locally for a bit see if I can work out what's going on.

**Comment by nulltoken** [comment]
@dazinator Sorry, I was unclear.

The exception above definitely looks like another issue.

The log I was referring to (and which is pasted in my comment) is extracted from the initial mail I received when your first issued your comment (which you may have edited meanwhile).

**Comment by dazinator** [comment]
@nulltoken ah yes - I did edit things - probably my bad - no worries.

**Comment by dazinator** [comment]
Ok the bug is here:

image

As to why `context.Repository.Info.WorkingDirectory` returns null I have no idea.. 

Any ideas?

**Comment by dazinator** [comment]
Also, I went to create a regression test to replicate this problem, but it hit me that I have absolutely no idea how to do such a thing. I guess I am just not familiar enough with GitVersion at this point.

So at the moment, to replicate this problem I simply put some command line arguments in the visual studio project configuration, and then ran the GitVersion.exe project.

**Pull request merged**
