### PR TITLE
fix Cannot find module 'argparse' issue

### LINKED ISSUE #1610: GitVersion .Net Core (Preview) Azure DevOps task error
Just tried out the new Azure DevOps task for .Net Core. It fails on a build with the following message

```
##[error]Unhandled: Cannot find module 'argparse'
```

### PR DESCRIPTION
**Pull request by flomader**
Resolves #1610

### CODE REVIEW

**Comment by arturcic** [comment]
LGTM!!

Unfortunately we cannot publish the pre-release versions as of now via CI, as we don't have valid token for publishing.
@JakeGinnivan we need valid token for marketplace publishing.

I'll merge the PR, thank you for your contribution!

**Comment by asbjornu** [comment]
@arturcic, I know @JakeGinnivan has too many GitHub notifications to follow them, so please try to reach out to him in other channels.

**Comment by jaq316** [comment]
Any luck on reaching @JakeGinnivan ?

**Comment by gep13** [comment]
@arturcic@asbjornu what exactly is required here?

**Comment by arturcic** [comment]
@gep13 we need a valid PAT (personal access token) on marketplace. I am a member on marketplace, but the PAT I generate is not valid, last time @JakeGinnivan has generated one. I talked to Jake few weeks ago when this issue first time appeared. I did not have time to ping him again.

**Comment by arturcic** [comment]
Would be great if I can generate myself a valid PAT

**Comment by asbjornu** [comment]
What would be required for you to generate a valid PAT, @arturcic?

**Comment by arturcic** [comment]
That's only an assumption, to have a valid PAT you need to have owner permissions, currently I have only contributor, Jake and Pascal have owner. Still I am able to manually publish the artifacts on marketsplace, but not from command line in a CI scenario

**Comment by gep13** [comment]
@arturcic ok, this is something we need to get sorted out. Are there any other permissions that are needed?

**Comment by gep13** [comment]
@asbjornu I reached out to @JakeGinnivan and he has issued @arturcic with a PAT that will get him started.  He mentioned that you are an Administrator of the VSTS Project.  Are you in a position to add @arturcic as an administrator as well (as well as everyone else on the team)?

**Comment by arturcic** [comment]
I got the new PAT from @JakeGinnivan, but it seems it's not valid :(

**Comment by gep13** [comment]
@arturcic doh! :-(  @asbjornu would you be able to have a look at this, to see if you can create a PAT, or ideally, add @arturcic to the package as well?

**Comment by asbjornu** [comment]
In [the settings for GitVersion on Azure DevOps](https://dev.azure.com/GitTools/GitVersion/_settings/), @arturcic is listed as an administrator already.

**Comment by arturcic** [comment]
That is right, but I need to be here https://marketplace.visualstudio.com/manage/publishers/gittools

**Comment by arturcic** [comment]
image

**Comment by gep13** [comment]
Perhaps @pascalberger can help in this regard as well?

**Comment by asbjornu** [comment]
Aha. I have no access there at all:

Screenshot 2019-04-10 at 10 56 12

Can @pascalberger please make @arturcic an owner then?

**Comment by gep13** [comment]
Sounds like it would be good to get yourself @asbjornu added in there as well 😄 Is there anyone else that should be added?  Is there a document that lists all the places that contributors to GitVersion need to be given access?  I think that this would be a good thing to have, as a reference for bringing on new people.  Perhaps this is something that @arturcic could compile, since he has gone through it most recently?

**Comment by arturcic** [comment]
Sure

**Comment by asbjornu** [comment]
Yep, I wouldn't mind having access, @gep13. Just need to get @pascalberger's attention. 😄

**Comment by pascalberger** [comment]
Where do I need to give you permissions? In the Azure DevOps organization you seem to be already an collection administrator @asbjornu. I failed to find where to set permissions for marketplace when I looked quickly. Do you know how to get there?

I'll be occupied with meetings the whole day, but try to have another look as soon as I find a few minutes.

**Comment by asbjornu** [comment]
@pascalberger, [it's in here](https://marketplace.visualstudio.com/manage/publishers/gittools) as @arturcic wrote in https://github.com/GitTools/GitVersion/pull/1631#issuecomment-481596896.

**Comment by pascalberger** [comment]
@asbjornu Mmh, I also get a 403 while accessing this site...

**Comment by gep13** [comment]
@pascalberger @asbjornu @arturcic I have reached out to @JakeGinnivan to see if he can offer any help here.

**Comment by JakeGinnivan** [comment]
Finally got the right permissions page thanks to the link @asbjornu posted the other day. I was in a totally different area trying to grant permissions..

@arturcic you are owner, I can't add @gep13 or @asbjornu because apparently `.co.uk` and `.no` are both not valid domains :P

**Comment by gep13** [comment]
@asbjornu my suspicion is that it is complaining because mine is an MSA with custom domain. I have passed on another email address to @jakeginnivan

**Comment by asbjornu** [comment]
My Gmail address might be considered valid, perhaps. I’ll DM it to you, @JakeGinnivan.

**Comment by mvrmoreira** [comment]
Nice!

**Comment by Nohcho** [comment]
Any progress on this one guys?

**Comment by arturcic** [comment]
I'll try to generate a new token and try to upload a vsix from command line to see if it works, I hope I can find some time today

**Comment by jaq316** [comment]
Any progress here?

**Comment by arturcic** [comment]
Unfortunately none, busy with other stuff for now, hopefully will have time to have a look. Sorry, doing only when I have some free time left, it's not my day by day job

**Comment by jaq316** [comment]
Ofcourse. Thank you. Wish I could contribute in solving this.

**Comment by jaq316** [comment]
Is there anything I can do to help this along?

**Comment by xzuttz** [comment]
This is ridiculous

**Comment by gep13** [comment]
>@xzuttz said...
This is ridiculous

This is open source. There are no guarantees when, or if, things well get done.  All time given to this repository and its tools is volunteer, and I would ask you to consider that when posting things like this.

**Comment by cyan198** [comment]
I tried today and I'm also having this issue in linux agent. I guess it hasn't released to marketplace?

Thanks.

**Comment by kmiterror** [comment]
Since it takes long to update the Azure DevOps task I have made a workaround. 
**Install .net core git version cli** 
Add ".NET Core" task to your build
Set Command to "Custom"
Set Custom Command to "tool"
Set Arguments to "install -g GitVersion.Tool  --version 5.0.0 --ignore-failed-sources"

**Use gitversion tool**
Add ".NET Core" task to your build
Set Command to "Custom"
Set Custom Command to "gitversion"
Set Arguments to "/output buildserver /nofetch"

In fact -g option in first step should not be used because it install gitversion globally. 
It might be a good enough workaround for most Azure DevOps users.

**Comment by arturcic** [comment]
@kmiterror I wonder why don't you use the latest task? https://marketplace.visualstudio.com/items?itemName=gittools.gitversion. You will have to unistall and then install back to the organization. Otherwise it's using the older cached version

**Comment by arturcic** [comment]
@cyan198 , it was already released

**Comment by kmiterror** [comment]
Ahh, I missed that one, I assumed that since the issue is not closed then it's not released yet. 
If that's the case my workaround is no longer needed.

**Pull request merged**
