### PR TITLE
GH2116: Fix GitHub Actions current branch and prevent fetch

### LINKED ISSUE #2116: GitHub Actions build fails with private GitHub repo and Dependabot PR
I've never had a problem with Dependabot PRs before, but then that's always been with public repos.

Now, with a private repo, the GitHub Actions `push` event succeeds, but the `pullrequest` event fails with `LibGit2Sharp.LibGit2SharpException: this remote has never connected`. 😕 

Relevant env vars:
```
GITHUB_ACTION=self
GITHUB_ACTIONS=true
GITHUB_ACTOR=dependabot-preview[bot]
GITHUB_BASE_REF=master
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_PATH=/github/workflow/event.json
GITHUB_HEAD_REF=dependabot/nuget/Microsoft.Extensions.Configuration.CommandLine-3.1.2
GITHUB_REF=refs/pull/3/merge
GITHUB_REPOSITORY=pharos/extensions-configuration
GITHUB_RUN_ID=42047370
GITHUB_RUN_NUMBER=41
GITHUB_SHA=00c1efad94a92ac038ca47d9b893c7991caaca23
GITHUB_WORKFLOW=Build
GITHUB_WORKSPACE=/github/workspace
HOME=/github/home
PWD=/github/workspace
RUNNER_OS=Linux
RUNNER_TEMP=/home/runner/work/_temp
RUNNER_TOOL_CACHE=/opt/hostedtoolcache
RUNNER_WORKSPACE=/home/runner/work/extensions-configuration
```
[build.log](https://github.com/GitTools/GitVersion/files/4227941/build.log)

### PR DESCRIPTION
**Pull request by gitfool**
(Hopefully) fixes #2116. 😉

### CODE REVIEW

**Comment by gitfool** [comment]
My bad. I'll fix the unit tests.

**Comment by arturcic** [comment]
LGTM!

**Comment by arturcic** [comment]
thank you so much for your contributions 👍 @gitfool

**Comment by gitfool** [comment]
My pleasure. 😁

**Pull request merged**
