### PR TITLE
Update version in project.json files

### LINKED ISSUE #647: Support for dotnet (prev. DNX) / .NET Core projects
In DNX / .NET Core projects the version is set via the `project.json` file [described here](https://github.com/aspnet/Home/wiki/Project.json-file) in the Metadata section. `AssemblyInfo.cs` on the other hand is gone. I'd like to use GitVersion with such projects.

### PR DESCRIPTION
**Pull request by droyad**
Added the `/updateprojectjson` switch to GitVersion.exe which replaces the version in Project.json files. Closes #647.

### CODE REVIEW

**Comment by dazinator** [comment]
This capability would be really nice to have. I would love to see this in GitVersion because project.json's are currently a fact of life, even though they are expected to go away at some point in the future.. What are thoughts opinions around this?

**Comment by gep13** [comment]
@dazinator I have started using this: https://github.com/sergeyzwezdin/magic-chunks/ As it integrates really nicely with Cake, which I am now using for all my builds.

Here is an example of updating a project.json file with it:

https://github.com/OctopusDeploy/CSProjToXProj/blob/master/build.cake#L110

**Comment by dazinator** [comment]
@gep13 - thanks for that, I haven't looked at Cake yet, but I like the fact you can use c# syntax! Unfortunately switching to a Cake build isn't an option for us at present, so I am looking for alternatives like this PR..

@droyad I have noticed a bit of a problem with this PR in that it can break the build as it doesn't deal with updating version numbers in project references. For example, if you have ProjectA.json which references ProjectB.json, then ProjectA.json will have this dependency entry:

```
{
"dependencies": {
 "ProjectB": "1.0.0-*"
}
```

This functionality updates the `version`'s of both projects, for example to `1.1.0-alpha1` and now the solution won't build because the dependencies section are invalid. So for using this to build a multi-project solution, I think this would need to be solved..

**Comment by gep13** [comment]
@dazinator what are you currently using to run GitVersion?

**Comment by droyad** [comment]
@dazinator I use just the wildcard to reference other projects, ie:
```
{
"dependencies": {
 "ProjectB": "*"
}
```

Are there any drawbacks to that approach?

**Comment by dazinator** [comment]
@gep13 - a team city command line step!

@droyad - ah yeah so I tried that myself before I posted but it didn't work.. i'll try again - if it works for you then i probably just need to clear the project.lock files or something.

**Comment by gep13** [comment]
>@dazinator said,,,
@gep13 - a team city command line step!

Gotcha.  I was going to say that if you were using any other type of build script, i.e. psake, or something like that, then Magic Chunks has some plugins for there too.  It isn't just limited to Cake usage.

**Comment by JakeGinnivan** [comment]
Fyi to reference other projects you can do:

```
{
"dependencies": {
 "ProjectB": { "target": "project" },
}
```

**Comment by JakeGinnivan** [comment]
Thoughts on https://github.com/ah-/dotnet-gitversion

We could move this into a new project as done in that repo?

**Comment by gep13** [comment]
Makes sense to me.

**Comment by asbjornu** [comment]
@JakeGinnivan: That looks like a great effort from @ah-. Can't we just move his repository into the GitTools organization and make it official?

**Comment by JakeGinnivan** [comment]
I think his repo is a port to dotnet core. I am happy for someone else to take the lead on this feature :)

**Comment by JakeGinnivan** [comment]
If you need something specific from me let me know

**Comment by onovotny** [comment]
I'm not sure this is needed anymore. Instead, cross-compile the existing GitVersionTask for net4 and NetCoreApp. Then it can be used directly by csproj everywhere as I describe in #1118

**Comment by droyad** [comment]
Agreed. With the move back to msbuild system, the classic ;) approach can be used.

**Comment by asbjornu** [comment]
Can this be closed, then?

**Comment by dazinator** [comment]
Does that require an upgrade from VS2015 to VS2017 in order to migrate from project.json back to msbuild? Just concerned that project.json files might remain for those stuck on vs2015 is so?

**Comment by onovotny** [comment]
`project.json` will only work with vs 2015 and the new tooling will only work with vs 2017. The tooling are preview tooling with vs 2015 and will not get any more updates. Moving to VS 2017 is really the only option.

**Comment by dazinator** [comment]
hmm ok.. I'm going to enjoy explaining that cost to my manager haha. How about the cross plat story, for example Linux.. will their be new tooling on Linux to replace project.json as well?

**Comment by onovotny** [comment]
All of the tooling is going to be csproj only, including cross platform. The current preview4 CLI tooling already supports the csproj.

**Comment by dazinator** [comment]
Ok cool, thanks for explaining @onovotny - project.json shall be consigned to the dustbin of history, and anyone stuck on it will have a migration path... sounds very sensible to close this issue :-)

**Comment by dazinator** [comment]
@gep13 - I ended up moving from team city to appveyor and cake in the end and using Magic Chunks. I don't regret it. Team City is now dead to me.

**Pull request closed without merging**
