### PR TITLE
Fix remark-lint

### PR DESCRIPTION
**Pull request by asbjornu**
This PR hopefully fixes the remark-lint trouble discovered in #2957.

### CODE REVIEW

**Comment by arturcic** [comment]
@asbjornu I think you need to update https://github.com/GitTools/GitVersion/blob/7584b6aee6a99363a9f03c7dd2abb816e34db257/.github/workflows/docs.yml#L7 to include also trigger for the `package.json` changes and also for the `docs.yml` file changes as well. Currently it does not get triggered. On more think to add, would be nice to cache the `node_modules` and invalidate the cache if any of `package.json` or `package-lock.json` files have changed

**Comment by asbjornu** [comment]
The Mergify failure should vanish once this is merged to `main`.

**Comment by arturcic** [comment]
OK, looks good to me. You can merge it

**Comment by asbjornu** [comment]
@arturcic although I can merge without an approved review, can you please approve it? 😄

**Review by arturcic — APPROVED** [review]

**Pull request merged**
