### PR TITLE
Address tag parsing

### PR DESCRIPTION
**Pull request by JakeGinnivan**
Opening PR to discuss changes highlighted in #495

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
There is a small issue (which is causing the test failure) that a tag without the prefix will fail to pass.

Changing the regex from `var match = Regex.Match(version, string.Format("^({0})(?<version>.*)$", tagPrefixRegex));` to `var match = Regex.Match(version, string.Format("^({0})?(?<version>.*)$", tagPrefixRegex));` (making the prefix optional) fixed the issue.

Thanks gain for the changes

**Comment by JakeGinnivan** [comment]
Merged into master via 50833b4900ad653ddabfade567d58c52ef669110

**Comment by Tungsten78** [comment]
@JakeGinnivan, I committed another pass to better illustrate what I was trying to accomplish. The intent was to have the TagPrefix denote whether to treat as optional.  This being the default should handle most legacy usages with the exception of those already carrying around the old default of "[vV]" in their GitVersionConfig.yaml.   Technically, this would be a breaking change to those people.

I apologize for having left loose ends with the failed test.  I'm only reiterating because I feel the partial inclusion of the "[vV]|" is leaving the code base a little off (since the ? within the regex makes this redundant).

**Comment by JakeGinnivan** [comment]
I get you. The only issue is if someone has run `git init` it dumps the default config into the config file (I probably should fix that).

Do you see an issue with leaving the default as `[vV]` and making it optional in the parser. The inclusion of the `^$` should fix the issues you describe?

**Comment by Tungsten78** [comment]
Yes as merged it corrects my issue. It is only the remnants of what I was trying to accomplish that have left a bad taste in my mouth. I agree with the backwards compatibility issue. I will rework my pull tomorrow as a cleanup only. Thanks.

**Comment by JakeGinnivan** [comment]
Thanks, sorry I missed part of what you were doing

**Comment by Tungsten78** [comment]
@JakeGinnivan Here is the cleanup I promised.

**Comment by JakeGinnivan** [comment]
@Tungsten78 could you submit a PR for this?

**Pull request closed without merging**
