### PR TITLE
Node execution engine

### PR DESCRIPTION
**Pull request by sandorfr**
Pull request addressing #909 with minimal changes. It replaces #1139

### CODE REVIEW

**Comment by sandorfr** [comment]
@pascalberger @JakeGinnivan Sorry I couldn't do it before. But there it is, a PR with only what's require to build the typescript and install the dependencies. I tried to fix the appveyor script but I'm not familiar with this at all, so I leave it up to you.

**Comment by JakeGinnivan** [comment]
Merged via 7760da9a609fe3b596fbe85fe6a8132c891b089b

Thanks, will get this published over the weekend when I try and release v4

**Comment by mitchdenny** [comment]
Hey @JakeGinnivan long time no talk. Is this version of the task/extension now deployed to the VSTS marketplace? I was trying to use GitVersion on a build but it wouldn't kick over on Linux.

**Comment by sandorfr** [comment]
I don't think it is, and libgit2sharp still needs to be update for it to actually run on MacOS/Linux

**Comment by JakeGinnivan** [comment]
Hey @mitchdenny, when we setup the builds there wasn't support for beta extensions on the marketplace, long weekend this weekend, hopefully get v4 out :) 

#1150 is tracking supporting beta though

**Pull request closed without merging**
