### PR TITLE
Change GitVersionInformation C# template ('const string' instead of 'static string')

### PR DESCRIPTION
**Pull request by kvasnevskiy**
Changed GitVersionInformation C# template from `static string` to `const string` as discussed in #3095. Also I tested this with reflection and I didn't find any problems, I am able to get GitVersionInformation through reflection, maybe I missed smth. But as was mentioned in #3095 this change should be breaking, so  if it's breaking please let me know what exactly stopped working and how I can test it.

### CODE REVIEW

**Comment by asbjornu** [comment]
@kvasnevskiy, the breaking change is **how** existing reflection code works. If we change from `static string` to `const string`, existing code that performs reflection to find the `GitVersionInformation` class and its data, will need to change.

**Comment by asbjornu** [comment]
So I'm not opposed to implement this, I just think we need to do it on `main` and fold it into v6 and not release it as a part of v5.

**Review by asbjornu — CHANGES_REQUESTED** [review]
I'm not opposed to implement this, I just think we need to do it on `main` and fold it into v6 and not release it as a part of v5.

**Comment by arturcic** [comment]
@kvasnevskiy right

**Comment by kvasnevskiy** [comment]
Closed and will reopen on `main` branch.

**Pull request closed without merging**
