### PR TITLE
Feature/task disk cache

### PR DESCRIPTION
**Pull request by JakeGinnivan**

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
@asbjornu I have rebased, made some further refactorings/cleanups and got the build green :)

Nice change, I ended up removing the in memory cache. Would love a follow up review just to make sure I have not messed something up.

**Comment by JakeGinnivan** [comment]
Superseeds  #711

**Comment by JakeGinnivan** [comment]
Gonna merge this now @asbjornu, if you see issues, lets fix them in another PR

**Comment by asbjornu** [comment]
@JakeGinnivan Thanks! I don't notice anything, but if I do, I'll make another PR. Glad to finally see this merged. It will speed up our builds considerably. :)

**Comment by JakeGinnivan** [comment]
I haven't got the release together yet, will do soon

**Comment by asbjornu** [comment]
@JakeGinnivan No rush. Looking forward to trying it out. :)

**Pull request merged**
