### PR TITLE
Feature project json for discussion (By Droyad)

### PR DESCRIPTION
**Pull request by dazinator**
I have been using @droyad 's branch with the project json feature, and it has proved very useful.

Just gonna have a go at getting checks passed so it can be merged.

### CODE REVIEW

**Comment by dazinator** [comment]
FORGET IT :(

**Comment by gep13** [comment]
@dazinator what happened?

**Comment by dazinator** [comment]
The failed checks with Travis and AppVeyor are going to take too much time for me to investigate right now. I had a quick glimpse at the first one, and it looked like AppVeyor is complaining about a missing release notes md file, and Travis actually gets as far as running the tests but for some reason the tests fail. I was hoping it might just be a simple merge but it looks like its not going to be. I'm also not fully familiar with AppVeypr or Travis yet so I am not the best person to look at this right now. The original PR is still open https://github.com/GitTools/GitVersion/pull/980

**Comment by gep13** [comment]
>@dazinator said...
 and it looked like AppVeyor is complaining about a missing release notes md file,

That is a known issue that I have an open PR to correct.  Likely not an issue with the work you have done.

>@dazinator said...
running the tests but for some reason the tests fail

This is likely nothing to do with you either. Have a look at the conversation here: https://github.com/GitTools/GitVersion/pull/1093#discussion_r88751098

**Comment by dazinator** [comment]
> That is a known issue that I have an open PR to correct. Likely not an issue with the work you have done.

Ah ok nice one, perhaps i'll revisit this again after then, if necessary.

>Likely not an issue with the work you have done.
Disclaimer: none of this is my work - this is all @droyad 's - i just thought I'd have a quick go at trying to get the checks passing so it could be integrated. Will accept defeat for now.

**Comment by asbjornu** [comment]
@dazinator: Thanks for giving this a go! Unfortunately, GitVersion (or rather, its CI pipeline) isn't in very good shape at the moment. I hope we have that fixed soon and that you can take another stab at rebasing this once the CI pipeline has been stabilised.

**Comment by JakeGinnivan** [comment]
Should be good to try again now :)

**Pull request closed without merging**
