### PR TITLE
(deps) update LibGit2Sharp 0.27.0-preview-0158

### PR DESCRIPTION
**Pull request by arturcic**

### CODE REVIEW

**Review by asbjornu — APPROVED** [review]
👍🏼 Do we have any existing issues that may be resolved by this upgrade?

**Comment by arturcic** [comment]
There is a fix in building of the native libs for macos arm64

**Comment by asbjornu** [comment]
This should resolve #2668, then?

**Comment by arturcic** [comment]
In theory yes. I'm not able to test this, but I think we can ask those with macos m1 to give it a try

**Pull request merged**
