### PR TITLE
Failing Unit Test for Issue #1844

### PR DESCRIPTION
**Pull request by WalkerCodeRanger**
Failing Unit Test for Issue #1844. Tests that the version is bumped after a prerelease tag when not doing so would put them out of order

### CODE REVIEW

**Comment by asbjornu** [comment]
Thanks, @WalkerCodeRanger. Just for fun, what happens if you change `VersioningMode` to `Mainline`?

**Comment by WalkerCodeRanger** [comment]
If you change `VersioningMode` to `Mainline` without changing anything else, you get:
```
System.NotSupportedException : Mainline development mode doesn't yet support pre-release tags on master
```

**Comment by asbjornu** [comment]
Ah, right.

**Comment by asbjornu** [comment]
Will the fix implemented in #2003 help with this problem in any way?

**Comment by asbjornu** [comment]
Alas, #2003 was just merged and an update of this branch did not help. 😞

**Comment by arturcic** [comment]
Closed in favor of #3445

**Pull request closed without merging**
