### PR TITLE
Exopose NoNormalize property for GitVersionTask

### PR DESCRIPTION
**Pull request by chuseman**

### CODE REVIEW

**Comment by arturcic** [comment]
LGTM! 
Thank you so much for your contributions, @chuseman

**Comment by fedebn** [comment]
how to use this property from jenkins?

**Comment by asbjornu** [comment]
@fedebn, good question. Looks like there's no `NoNormalize` switch for the command line, @arturcic, @chuseman?

**Comment by fedebn** [comment]
> @fedebn, good question. Looks like there's no NoNormalize switch for the command line, @arturcic, @chuseman?

In order to disable the normalizing procedure it is necessary to change the property GitVersion_NoNormalizeEnabled on the jenkins manchine in GitVersionTask.props.
From:
<GitVersion_NoNormalizeEnabled Condition="$(GitVersion_NoNormalizeEnabled) == ''">false</GitVersion_NoNormalizeEnabled> 
To:
<GitVersion_NoNormalizeEnabled Condition="$(GitVersion_NoNormalizeEnabled) == ''">ture</GitVersion_NoNormalizeEnabled> 
the file is located in the nuget packages folder:
nuget\packages\gitversiontask\5.1.3\build

**Comment by fedebn** [comment]
> LGTM!
> Thank you so much for your contributions, @chuseman

I have used the property on my jenkins slave, but i can not build

gitversiontask\5.1.3\build\GitVersionTask.targets(65,9): warning : It looks like the branch being examined is a detached Head pointing to commit 'e148343'. Without a proper branch name GitVersion cannot determine the build version

C:\Program Files\dotnet\sdk\2.2.107\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4044: The "GetAssemblyVersion" task was not given a value for the required parameter "NuGetVersion".

**Comment by asbjornu** [comment]
@fedebn, you can use this in the latest pre-release builds of 5.1.4, but if you need a stable one you have to wait a bit until we have that finished up.

**Comment by fedebn** [comment]
I have teste latest official release, work properly, and speed up my build on jenkins slave

**Comment by asbjornu** [comment]
@fedebn, thanks for reporting back.

**Pull request merged**
