### PR TITLE
Lock file

### LINKED ISSUE #1031: LibGit2Sharp.LockedFileException: The index is locked. This might be due to a concurrent or crashed process
Wasn't sure if this was an issue or whether we shouldn't be using `msbuild /m` to enable concurrent builds.

```
[11:45:48]  [BuildSolution]     17>MSBUILD : warning : WARN [09/02/16 1:45:48:65] Could not determine assembly version: LibGit2Sharp.LockedFileException: The index is locked. This might be due to a concurrent or crashed process [Y:\Work\refs\heads\master\source\Octopus.E2ETests\Octopus.E2ETests.csproj]
[11:45:48]  [BuildSolution] MSBUILD : warning :    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) [Y:\Work\refs\heads\master\source\Octopus.E2ETests\Octopus.E2ETests.csproj]
[11:45:48]  [BuildSolution] MSBUILD : warning :    at LibGit2Sharp.Core.Proxy.git_checkout_tree(RepositoryHandle repo, ObjectId treeId, GitCheckoutOpts& opts) [Y:\Work\refs\heads\master\source\Octopus.E2ETests\Octopus.E2ETests.csproj]
[11:45:48]  [BuildSolution] MSBUILD : warning :    at LibGit2Sharp.Repository.CheckoutTree(Tree tree, IList`1 paths, IConvertableToGitCheckoutOpts opts) [Y:\Work\refs\heads\master\source\Octopus.E2ETests\Octopus.E2ETests.csproj]
[11:45:48]  [BuildSolution] MSBUILD : warning :    at LibGit2Sharp.Repository.Checkout(Tree tree, CheckoutOptions checkoutOptions, String refLogHeadSpec) [Y:\Work\refs\heads\master\source\Octopus.E2ETests\Octopus.E2ETests.csproj]
[11:45:48]  [BuildSolution] MSBUILD : warning :    at LibGit2Sharp.Repository.Checkout(Branch branch, CheckoutOptions options) [Y:\Work\refs\heads\master\source\Octopus.E2ETests\Octopus.E2ETests.csproj]
[11:45:48]  [BuildSolution] MSBUILD : warning :    at LibGit2Sharp.Repository.Checkout(String committishOrBranchSpec, CheckoutOptions options) [Y:\Work\refs\heads\master\source\Octopus.E2ETests\Octopus.E2ETests.csproj]
[11:45:48]  [BuildSolution] MSBUILD : warning :    at GitTools.Git.GitRepositoryHelper.EnsureLocalBranchExistsForCurrentBranch(Repository repo, String currentBranch) [Y:\Work\refs\heads\master\source\Octopus.E2ETests\Octopus.E2ETests.csproj]
[11:45:48]  [BuildSolution] MSBUILD : warning :    at GitTools.Git.GitRepositoryHelper.NormalizeGitDirectory(String gitDirectory, AuthenticationInfo authentication, Boolean noFetch, String currentBranch) [Y:\Work\refs\heads\master\source\Octopus.E2ETests\Octopus.E2ETests.csproj]
[11:45:48]  [BuildSolution] MSBUILD : warning :    at GitVersion.GitPreparer.Initialise(Boolean normaliseGitDirectory, String currentBranch) [Y:\Work\refs\heads\master\source\Octopus.E2ETests\Octopus.E2ETests.csproj]
[11:45:48]  [BuildSolution] MSBUILD : warning :    at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig) [Y:\Work\refs\heads\master\source\Octopus.E2ETests\Octopus.E2ETests.csproj]
[11:45:48]  [BuildSolution] MSBUILD : warning :    at GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication) [Y:\Work\refs\heads\master\source\Octopus.E2ETests\Octopus.E2ETests.csproj]
```

This occurs on TeamCity `10.0.0` building ~30 projects. We've only just upgraded to `GitVersionTask.3.6.3` from `GitVersionTask.3.6.1` which had the `gitversion_cache` issue.

In the meantime I'll try some more builds and see if it recurs frequently.

### LINKED ISSUE #1381: GitVersionTask Parallel restore issue when multi targeting
I am noticing this issue in my NETSTANDARD PR branch, but I think it might impact master as well (although not tested master directly I am inferring it is a problem)

The issue is, the following target runs when restoring:

```
  <Target Name="WriteVersionInfoToBuildLog" BeforeTargets="DispatchToInnerBuilds;GenerateNuspec;_GenerateRestoreProjectSpec" Condition="$(WriteVersionInfoToBuildLog) == 'true'">
    <WriteVersionInfoToBuildLog SolutionDirectory="$(GitVersionPath)" NoFetch="$(GitVersion_NoFetchEnabled)"/>
  </Target>
```

The `WriteVersionInfoToBuildLog` msbuild task ends up calling `ExecuteGitVersion` which ends up using `libgit2sharp`.

If you are restoring a solution with dotnet restore (I am not sure about /T:Restore but I assume it's the same?) restoration happens in parallel unless you opt out via `dotnet restore --disable-parallel` switch.

Because of this, I am seeing libgit2sharp throw errors about locking as it's being used in parallel to inspect the same repo:

https://ci.appveyor.com/project/dazinator/gitversion-pr1269/build/0.1.1+5.build.1#L32

### PR DESCRIPTION
**Pull request by asbjornu**
A rebase and `dotnet format` fixed version of #2333. Hopefully the tests turn green so we can make this available in a beta for testing.

Resolves #2333. Hopefully fixes #1031. Hopefully fixes #1381.

### CODE REVIEW

**Comment by dojo90** [comment]
push 🎉

**Review by arturcic — CHANGES_REQUESTED** [review]

**Comment by dazinator** [comment]
Lot of work here!
My only suggestion would be to make the locking abstraction more general purpose, and have the file based locking, one implementation:

```
ILocker locker = new FileLocker(); // we can switch implementations
using(var lock = locker.Aquire());
{

// do stuff here

}
```

The reason for that is that we might want to switch to other sorts of locking if we encounter issues with file based locking. For example, on .net core we may want to try a global (named) mutex implementation: https://docs.microsoft.com/en-us/dotnet/standard/threading/mutexes#local-and-system-mutexes


Other than that, I couldn't see any tests to excercise the file locker - I assume we are relying on higher level integration tests to flag this during a CI build?

**Review by dazinator — COMMENTED** [review]
Lot of work here!
My only suggestion would be to consider making he locking abstraction more general purpose, and have the "file based" locking be one implementation:

ILocker locker = new FileLocker(); // we can switch implementations
using(var lock = locker.Aquire());
{

// do stuff here

}
The reason for that is that we might want to switch to other sorts of locking if we encounter issues with file based locking. For example, on .net core we may want to try a global (named) mutex implementation: https://docs.microsoft.com/en-us/dotnet/standard/threading/mutexes#local-and-system-mutexes

Other than that, I couldn't see any tests specifically for the file locker - I assume we are relying on higher level integration tests to verify that it works?

**Comment by arturcic** [comment]
@asbjornu looks like the Locking interfaces are not used in our code base. 
I guess this one should be made a draft PR as it's not finished?

**Comment by asbjornu** [comment]
> @asbjornu looks like the Locking interfaces are not used in our code base.

Good find! I haven't studied the code enough to discover that yet.

> I guess this one should be made a draft PR as it's not finished?

Yes, indeed.

**Comment by riksking** [comment]
Hi, All.

Can you publish beta version with this fix.
I'm ready to test it.

**Comment by arturcic** [comment]
@riksking this is still a draft, the code implementation is not finished

**Comment by dieterv** [comment]
@asbjornu starting from your asbjornu:feature/lockfile branch, I rebased and applied the following changes:
- [Rename methods to follow Pascal Case](https://github.com/dieterv/GitVersion/commit/f76077c1bb00cd33bf0b1a060d394de1e3ed8192)
- [Draft: Enable file locking](https://github.com/dieterv/GitVersion/commit/9cdbd4fadd2222549b0cd2a5a2be9f73a3b2876e)

I've been using GitVersion.MsBuild and GitVersion.CommandLine nuget packages with these two changes since yesterday for our CI builds on our private GitLab instance in addition to enabling parallel builds (msbuild /m parameter). I can confirm I haven't seen any `error : LockedFileException: the index is locked; this might be due to a concurrent or crashed process` message since doing so :grin: :tada:

**Comment by asbjornu** [comment]
#2581 should fix this in a satisfactory manner. If anyone wants to pick this up, please fork, complete the implementation and submit a new pull request.

**Pull request closed without merging**
