### PR TITLE
Make fields `readonly` where applicable

### LINKED ISSUE #2758: [Improvement] Add missing `readonly` when applicable
There are a couple of locations in the codebase where some declared fields could be marked as `readonly` because they are only initialized in the constructor.

## Detailed Description

List of files:
- GlobbingResolver.cs
- OverrideConfigOptionParser.cs
- ProgramFixture.cs
- GitPreparer.cs
- RetryAction.cs
- VersionInBranchNameVersionStrategy.cs
- GitRepository.cs
- GitRepositoryInfo.cs

### PR DESCRIPTION
**Pull request by Evangelink**
Fixes #2758

### CODE REVIEW

**Review by asbjornu — APPROVED** [review]

**Comment by Evangelink** [comment]
The build error doesn't seem to relate to this PR changes, could you rerun the failing jobs please?

**Comment by Evangelink** [comment]
@asbjornu It seems that the failing tests are tests failing on the `main` branch. I have create separate issues for them.

When fixed we should be able to move forward this (and the analyzer) PRs.

**Comment by asbjornu** [comment]
@Evangelink, all tests are green. Which PR do you want merged first? This or #2761?

**Comment by Evangelink** [comment]
@asbjornu Let's go with this one.

**Pull request merged**
