### PR TITLE
Add NuGetPreReleaseTag variable

### PR DESCRIPTION
**Pull request by qetza**
Issue #834

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
The only comment is maybe we should have a v2 variable as well. The idea for the v2 variable is that when NuGet adds proper SemVer support, the NuGet variable will stop padding but the v2 variable won't.

**Comment by qetza** [comment]
Will do when i'm back home :smile:

**Comment by qetza** [comment]
Done

**Comment by JakeGinnivan** [comment]
Was a good move asking for the v2 var ask the change to SemVer 2 is underway for NuGet. https://emgarten.com/2016/08/09/semver-2-0-0-with-nuget-3-5-0-rc1/

**Pull request merged**
