### PR TITLE
Turn Microsoft.Extensions.DependencyInjection into a private dependency

### LINKED ISSUE #2020: Dependency Microsoft.Extensions.DependencyInjection copied to project output folder
GitVersionTask v5.1.3 introduces a dependency on `Microsoft.Extensions.DependencyInjection` for .NETFramework 4.7.2 as well as .NETCoreapp 2.1 and 3.1. 

After retargeting my solution to net472, the above dependency (and indirectly `Microsoft.Extensions.DependencyInjection.Abstraction`) is added to my solution as well. Further, both DLLs are copied to the project output folders, where they will be harvested by my WiX installer and, thus, included in the redistributable I am building.

I would expect `GitVersionTask` and all of its dependencies to be build-time dependencies. Like `GitVersionTask` itself, those DLLs should not be copied to the output folders.

### PR DESCRIPTION
**Pull request by ThomasBarnekow**
This commit adds `PrivateAssets="All"` to the `PackageReference` for the
`Microsoft.Extensions.DependencyInjection` NuGet package.

Fixes #2020.

### CODE REVIEW

**Comment by arturcic** [comment]
Is it possible to have a targetframework == net472 and one !=472? Meaning to have 2 options only

**Comment by ThomasBarnekow** [comment]
Sure, I thought about that as well but then decided to be explicit for each target framework.

Will make the change.

**Comment by arturcic** [comment]
LGTM!

**Comment by arturcic** [comment]
Thank you so much for your contributions, @ThomasBarnekow :+1:

**Comment by ThomasBarnekow** [comment]
You are welcome, @arturcic. Thanks for merging so quickly!

**Comment by arturcic** [comment]
Let me know if the published version when available is working for you

**Comment by ThomasBarnekow** [comment]
@arturcic, I just checked the published version and it works for me. There is still the known issue of updating the NuGet package for projects using `packages.config`, but outside of that, the dependency on `Microsoft.Extensions.DependencyInjection` is removed.

**Pull request merged**
