### PR TITLE
Support for space character in the VSTS Agent working directory

### LINKED ISSUE #1075: Build fails when VSTS Agent has a space character in it's working directory
My build works fine on a hosted agent however our local agent is installed at 'd:\Apps\VSTS Agent'.  It looks like the arguments passed to GitVersion.exe have not been quoted so it is getting a bit confused.  

This causes the build to fail.

The relevant bit of the build log file:
```
2016-10-31T02:28:31.9254640Z Current Directory:  D:\Apps\VSTS Agent\_work\_tasks\GitVersion_e5983830-3f75-11e5-82ed-81492570a08e\3.6.3
2016-10-31T02:28:31.9264643Z 
2016-10-31T02:28:31.9264643Z 
2016-10-31T02:28:31.9264643Z Sources Directory:  D:\Apps\VSTS Agent\_work\1\s
2016-10-31T02:28:31.9264643Z 
2016-10-31T02:28:31.9264643Z 
2016-10-31T02:28:31.9354715Z Invoking GitVersion with D:\Apps\VSTS Agent\_work\1\s /output buildserver /nofetch /updateassemblyinfo true
2016-10-31T02:28:31.9354715Z 
2016-10-31T02:28:31.9354715Z 
2016-10-31T02:28:31.9404729Z D:\Apps\VSTS Agent\_work\_tasks\GitVersion_e5983830-3f75-11e5-82ed-81492570a08e\3.6.3\GitVersion.exe D:\Apps\VSTS Agent\_work\1\s /output buildserver /nofetch /updateassemblyinfo true
2016-10-31T02:28:31.9424756Z ##[debug]Entering ProcessWrapper.CreateStartInfo
2016-10-31T02:28:31.9434751Z ##[debug]   workingFolder = 
2016-10-31T02:28:31.9434751Z ##[debug]   filename = D:\Apps\VSTS Agent\_work\_tasks\GitVersion_e5983830-3f75-11e5-82ed-81492570a08e\3.6.3\GitVersion.exe
2016-10-31T02:28:31.9434751Z ##[debug]   arguments = D:\Apps\VSTS Agent\_work\1\s /output buildserver /nofetch /updateassemblyinfo true
2016-10-31T02:28:31.9434751Z ##[debug]Leaving ProcessWrapper.CreateStartInfo
2016-10-31T02:28:31.9454765Z ##[debug]ProcessWrapper.Start - enter
2016-10-31T02:28:31.9454765Z ##[debug]ProcessWrapper.Start - starting process
2016-10-31T02:28:31.9484786Z ##[debug]ProcessWrapper.Start - process started
2016-10-31T02:28:31.9514820Z ##[debug]ProcessWrapper.Start - leave
2016-10-31T02:28:32.0035183Z WARN [10/31/16 13:28:31:99] The working directory 'D:\Apps\VSTS' does not exist.
2016-10-31T02:28:32.0035183Z INFO [10/31/16 13:28:32:00] IsDynamicGitRepository: False
2016-10-31T02:28:32.0185294Z ERROR [10/31/16 13:28:32:01] An unexpected error occurred:
```

I will try to fix the issue and submit a pull request

### PR DESCRIPTION
**Pull request by johanclasson**
Fixes #1075.

Its a such small change that I have nothing else to add. :)

### CODE REVIEW

**Comment by pascalberger** [comment]
Thanks @johanclasson! LGTM

The build failures should not be related to your changes.

**Comment by johanclasson** [comment]
Great, thanks!

**Comment by pascalberger** [comment]
But I think we need to fix the build first and rebase this before we can merge. Will let you know as soon as this is done.

**Comment by johanclasson** [comment]
Sure!

**Pull request merged**
