### PR TITLE
Avoid set-env environment warning during build log generation

### LINKED ISSUE #2421: [Bug] GenerateBuildLogOutput for Github actions uses deprecated set-env command
**Describe the bug**

GitHub Actions is deprecating set-env and add-path commands as outlined by

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Therefore starting from version 2.273.5 of the runner `GenerateBuildLogOutput` outputs

image

Environment files should be used instead

https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files

## Expected Behavior

Use env files to not trigger the warning

## Actual Behavior

image

## Possible Fix

See PR

## Steps to Reproduce

Run a build with GitVersion using GitHub actions

## Your Environment

- Version Used:
- Operating System and version (Windows 10, Ubuntu 18.04):
- Link to your project:
- Link to your CI build (if appropriate):

### PR DESCRIPTION
**Pull request by danielmarbach**
GitHub Actions is deprecating set-env and add-path commands as outlined by

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Therefore starting from version 2.273.5 of the runner `GenerateBuildLogOutput` outputs

image

Environment files should be used instead

https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files

## Description

see above

## Related Issue

Fixes #2421 and GitTools/actions#213.
## How Has This Been Tested?

No, I edited the file online and did not try to build and intermediate package to a private feed and then use that in my code. We should be able though to see the impact on the build on this project. I'll update the screenshots as soon as this compiles

## Screenshots (if appropriate):

Also happens on the build of this project, see

image

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by danielmarbach** [comment]
I wasn't sure if `echo` is needed or not. I assumed things will be echoed. Let me know if my assumptions are correct or not

**Comment by danielmarbach** [comment]
The new output

```
 Executing GenerateBuildLogOutput for 'GitHubActions'.
"GitVersion_Major=5" >> $GITHUB_ENV
"GitVersion_Minor=4" >> $GITHUB_ENV
"GitVersion_Patch=0" >> $GITHUB_ENV
"GitVersion_PreReleaseTag=PullRequest2422.136" >> $GITHUB_ENV
"GitVersion_PreReleaseTagWithDash=-PullRequest2422.136" >> $GITHUB_ENV
"GitVersion_PreReleaseLabel=PullRequest2422" >> $GITHUB_ENV
"GitVersion_PreReleaseNumber=136" >> $GITHUB_ENV
"GitVersion_WeightedPreReleaseNumber=30136" >> $GITHUB_ENV
"GitVersion_FullBuildMetaData=Branch.pull-2422-merge.Sha.0de23a7b9331d75d9ffa1a3eaf44db4dc2509800" >> $GITHUB_ENV
"GitVersion_MajorMinorPatch=5.4.0" >> $GITHUB_ENV
"GitVersion_SemVer=5.4.0-PullRequest2422.136" >> $GITHUB_ENV
"GitVersion_LegacySemVer=5.4.0-PullRequest2422-136" >> $GITHUB_ENV
"GitVersion_LegacySemVerPadded=5.4.0-PullRequest2422-0136" >> $GITHUB_ENV
"GitVersion_AssemblySemVer=5.4.0.0" >> $GITHUB_ENV
"GitVersion_AssemblySemFileVer=5.4.0.0" >> $GITHUB_ENV
"GitVersion_FullSemVer=5.4.0-PullRequest2422.136" >> $GITHUB_ENV
"GitVersion_InformationalVersion=5.4.0-PullRequest2422.136+Branch.pull-2422-merge.Sha.0de23a7b9331d75d9ffa1a3eaf44db4dc2509800" >> $GITHUB_ENV
"GitVersion_BranchName=pull/2422/merge" >> $GITHUB_ENV
"GitVersion_EscapedBranchName=pull-2422-merge" >> $GITHUB_ENV
"GitVersion_Sha=0de23a7b9331d75d9ffa1a3eaf44db4dc2509800" >> $GITHUB_ENV
"GitVersion_ShortSha=0de23a7" >> $GITHUB_ENV
"GitVersion_NuGetVersionV2=5.4.0-pullrequest2422-0136" >> $GITHUB_ENV
"GitVersion_NuGetVersion=5.4.0-pullrequest2422-0136" >> $GITHUB_ENV
"GitVersion_NuGetPreReleaseTagV2=pullrequest2422-0136" >> $GITHUB_ENV
"GitVersion_NuGetPreReleaseTag=pullrequest2422-0136" >> $GITHUB_ENV
"GitVersion_VersionSourceSha=08a43ede0b292c8ce2178b3d305587f151a2bdf4" >> $GITHUB_ENV
"GitVersion_CommitsSinceVersionSource=136" >> $GITHUB_ENV
"GitVersion_CommitsSinceVersionSourcePadded=0136" >> $GITHUB_ENV
"GitVersion_CommitDate=2020-10-09" >> $GITHUB_ENV
  INFO [10/09/20 7:59:51:84] Done writing 
Finished executing task: Build
```

**Comment by asbjornu** [comment]
Thanks for fixing this, @danielmarbach! ❤️ 

Thanks for fixing the build, @arturcic. 🙏

**Comment by danielmarbach** [comment]
You are most welcome

**Pull request merged**
