### PR TITLE
TagPrefix cleanup

### PR DESCRIPTION
**Pull request by Tungsten78**
Cleaning up a few leftovers that resulted from a partial merge of pull request #496.  As before, TagPrefix is always considered optional.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
@SimonCropp this PR seems to be causing a PEVerify error. https://ci.appveyor.com/project/GitTools/gitversion/build/0.0.60#L204

Any ideas? Wondering if it's the const?

**Comment by Tungsten78** [comment]
Not sure what this error is:

MSBUILD : error : Fody: PEVerify of the assembly failed. [C:\projects\gitversion\GitVersionCore\GitVersionCore.csproj]

**Comment by Tungsten78** [comment]
I'm seeing the error on my side with a solution rebuild.  If I remove the const it does indeed go away.

There's a bit more info in the error:
```
1>MSBUILD : error : [IL]: Error: [C:\Projects\GitVersion\GitVersion\GitVersionCore\bin\Release\GitVersionCore.dll : GitVersion.Config::DebuggerDisplay][offset 0x00000026] Unable to resolve token.(Error: 0x80131869)
```

@JakeGinnivan Would you rather me just rid the const and hardcode the "[vV]" as it was?

**Comment by Tungsten78** [comment]
I updated the branch to use an ```internal const``` instead.  This gets us past the validation error and is still accessible to the test library because of the existing ```[assembly:InternalsVisibleTo("GitVersionCore.Tests")]```

**Pull request merged**
