### PR TITLE
Mono support

### LINKED ISSUE #264: [Question] Support for Mono
Does GitVersion support running under Mono?

If not, are there any plans to support?

### PR DESCRIPTION
**Pull request by asbjornu**
This PR builds on @BeeWarloc's work in #638 and fixes #264. I've added a [Travis build](https://travis-ci.org/asbjornu/GitVersion) so we can have continuous integration testing on Linux. I don't think I've broken backward compatibility with anything, so it should be safe to merge this into `master` and release as a `3.x`. I think adding Linux support is so important that it can't wait for version 4.

That being said, the tests on Travis fail with the following exception:

```c#
System.TypeInitializationException : The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
  ----> System.DllNotFoundException : NativeBinaries/linux/amd64/libgit2-785d8c4.so
  at LibGit2Sharp.Core.Proxy.git_repository_init_ext (LibGit2Sharp.Core.FilePath workdirPath, LibGit2Sharp.Core.FilePath gitdirPath, Boolean isBare) <0x4188cb20 + 0x00058> in <filename unknown>:0 
  at LibGit2Sharp.Repository.Init (System.String path, Boolean isBare) <0x4188b080 + 0x0005a> in <filename unknown>:0 
  at LibGit2Sharp.Repository.Init (System.String path) <0x4188b050 + 0x00016> in <filename unknown>:0 
  at EmptyRepositoryFixture.CreateNewRepository (System.String path) <0x4188afb0 + 0x00017> in <filename unknown>:0 
  at RepositoryFixtureBase..ctor (System.Func`2 repoBuilder, GitVersion.Config configuration) <0x4188acd0 + 0x0002b> in <filename unknown>:0 
  at EmptyRepositoryFixture..ctor (GitVersion.Config configuration) <0x4188ac00 + 0x000ad> in <filename unknown>:0 
  at PullRequestInTeamCityTest.GivenARemoteWithATagOnMaster_AndAPullRequestWithTwoCommits_AndBuildIsRunningInTeamCity_VersionIsCalculatedProperly (System.String pullRequestRef) <0x418931b0 + 0x0009b> in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x41733ab0 + 0x000b7> in <filename unknown>:0 
--DllNotFoundException
  at (wrapper managed-to-native) LibGit2Sharp.Core.NativeMethods:git_libgit2_init ()
  at LibGit2Sharp.Core.NativeMethods+LibraryLifetimeObject..ctor () <0x4188d390 + 0x00010> in <filename unknown>:0 
  at LibGit2Sharp.Core.NativeMethods..cctor () <0x4188d120 + 0x00159> in <filename unknown>:0 
```

I think this is the problem being described in libgit2/libgit2sharp#1170, so when that's closed and LibGit2Sharp upgraded in this PR, Travis should happily execute the build and paint all tests in a beautiful, green color. I hope @nulltoken can verify this?

Unless libgit2/libgit2sharp#1170 takes an ice age to complete, I think merging this PR should wait until it's fixed. Oh and thanks to @gep13 for the moral support and tips on Gitter. :smile:

### CODE REVIEW

**Comment by asbjornu** [comment]
I can't see why the build is failing on AppVeyor. Ideas would be highly appreciated!

**Comment by asbjornu** [comment]
Ugh. Seems like 6caae2e11a7cc13ca8f46ad78a1461cc8f262cae is causing trouble with NUnit 3.2. I can't get the parametrization of `AssemblyInfoBuilderTests` to work:

> `AssemblyInfoBuilderTests.VerifyAssemblyVersion_Major`: The `sourceName` specified on a `ValueSourceAttribute` must refer to a non null static field, property or method.

@apmorton, @JakeGinnivan, do you have idea on how to fix this?

**Comment by apmorton** [comment]
I'm on mobile now, so this is just a guess. I can look into it further
later today.

On line 56, make compilers static.

private readonly ICompiler[] compilers = new ICompiler[]

I vaguely remember having issues with that being static, which is why it
ended up being private readonly, but I might be mistaken.

Austin

**Comment by apmorton** [comment]
Ignore me - github delivered that email notification waaaaay late :)

**Comment by asbjornu** [comment]
@apmorton Thanks for checking in! A bit of searching and poking brought me to nunit/nunit#947 which made me realize that `ValueSourceAttributes` expects the referenced field to be `static` in NUnit 3. So, all good! :smile:

**Comment by asbjornu** [comment]
This PR depends on GitTools/GitTools.Core#29 being merged and pre-released on NuGet so every dependency in the chain is built against [LibGit2Sharp version `0.23.0-pre20150419160303`](https://www.nuget.org/packages/LibGit2Sharp/0.23.0-pre20150419160303).

**Comment by JakeGinnivan** [comment]
Everything downstream has been merged/updated. Gonna try and push out a release, if there is any further work then we can just do a patch release :) There are other fixes I want to get out

**Pull request merged**
