### PR TITLE
Add support for VSO agent #546

### PR DESCRIPTION
**Pull request by onovotny**

### CODE REVIEW

**Comment by onovotny** [comment]
This addresses #546 and #560 to add support for the VSO agent

**Comment by pascalberger** [comment]
Awesome! Would be great if you could also update https://github.com/GitTools/GitVersion/blob/master/docs/more-info/build-server-setup/tfs-build-vnext.md with documentation how to setup GItVersion in TFS Build 2015 (and what restrictions currently apply)

**Comment by johnkattenhorn** [comment]
Thanks @onovotny, I'll definitely try to check this out this week (Feet currently held to fire :-) ).

**Comment by onovotny** [comment]
I'll add something to those docs -- it would also be nice to package this up as a VSO Build step, but the docs are still virtually non-existent.

https://github.com/Microsoft/tfs-cli/blob/master/docs/buildtasks.md

From what I can tell, the easiest way would be to create a package that includes the GitVersionTask.exe along with its containing json/packaging and push that to the vso gallery. Then it's just a matter of updating that when new versions are published.

**Comment by pascalberger** [comment]
A build step would be nice. Unfortunately currently there's nothing like a VSO Gallery available. There exists the [tfs-cli tool](https://github.com/Microsoft/tfs-cli) to upload custom build tasks to a VSO tenant.
Therefore I assume this repo (or a new one) would be the best place to host the build step releases at the moment.

Addint the GitVersion.exe in the build task should be easy to achieve. You can look at [Sonar build task](https://github.com/Microsoft/vso-agent-tasks/tree/master/Tasks/SonarQubePreBuild) or the  [OctoTFS build task](https://github.com/OctopusDeploy/OctoTFS/tree/master/source/CustomBuildSteps/CreateOctopusRelease) as samples. Maybe another possibility would be to set a demand in the `task.json` to check for GitVersion existance on the server, but this would require manual installation of GitVersion on the agent and setting some environment variables.

**Comment by onovotny** [comment]
Agreed, but that should be a separate issue -- I'll file one for that. I think this can get merged in once I update the docs.

**Comment by onovotny** [comment]
Closing this PR, #562 should be used instead as it contains everything needed to work with VSO.

**Pull request closed without merging**
